// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Routes, loadings;

  Routes = (function() {
    function Routes() {
      var that;
      this.history = [];
      this.history.push(window.location.href);
      this.current = 0;
      that = this;
      window.onpopstate = function(e) {
        return that.pop(e);
      };
    }

    Routes.prototype.navigate = function(url) {
      var current;
      if (!url || url === void 0 || url === null) {
        throw new Error("Invalid Url Navigation");
      }
      url = url.split('?')[0];
      current = this.history[this.current];
      if (current !== url) {
        window.history.pushState({
          previous: {
            index: this.current,
            url: current
          },
          url: url
        }, '', url);
        this.current = this.history.push(url) - 1;
      }
    };

    Routes.prototype.pop = function(e) {
      return window.location.reload();
    };

    return Routes;

  })();

  window.renderHtmlCell = function(d) {
    return d;
  };

  window.routes = new Routes;

  window.beginRequest = function(promise) {
    criaLoading("page-wrapper");
    return promise.complete(function() {
      return destroiLoading("page-wrapper");
    });
  };

  window.drawCallback = function() {
    var draw, _i, _len, _results;
    $('.dataTables_filter button, .btn-create').remove();
    _results = [];
    for (_i = 0, _len = draws.length; _i < _len; _i++) {
      draw = draws[_i];
      _results.push($(draw.el).append(draw.content));
    }
    return _results;
  };

  jQuery.ajaxPrefilter(function(options, originalOptions, xhr) {
    if (options.url === 'ajax/default.asp') {
      options.url = originalOptions.url = "" + appPath + "../" + options.url;
    }
    if (options.url === 'ajax/login/verificaSessao.asp' || options.url === '../_inc/ajax/login/verificaSessao.asp') {
      options.url = originalOptions.url = "" + appPath + "../" + options.url;
      return xhr.done(function(data) {
        if (!data.sessao) {
          modalAlerta("Sessão Expirada", "Sua sessão expirou!");
          return setTimeout(function() {
            return window.location.assign("" + appPath + "../login.asp");
          }, 5000);
        }
      });
    }
  });

  $(function() {
    var prop, selectedSetor;
    selectedSetor = null;
    prop = false;
    window.ddlChange = function() {
      var cnes, d, ma, nome, txt;
      if (this.value === '') {
        return;
      }
      txt = $(this).text();
      d = txt.split(' / ');
      ma = d[0].trim();
      cnes = d[1].split(' - ')[0].trim();
      nome = d[1].trim();
      $(this).text(ma).data({
        setor: {
          cnes: cnes,
          nome: nome
        }
      });
      prop = true;
      if (this.selected && !selectedSetor) {
        selectedSetor = cnes;
        $('[name=unidadeCred]').val(cnes);
      } else if (selectedSetor !== cnes) {
        $(this).attr('disabled', true);
      }
      $('[name=unidadeCred]').trigger('change');
      prop = false;
    };
    $('select#idMicroAreaUnidade option, select#ItemVinc option').each(ddlChange);
    $(document).on('change', '[name=unidadeCred]', function() {
      var set;
      set = $(this).val();
      if (set !== selectedSetor && !prop) {
        $('select#idMicroAreaUnidade, select#ItemVinc').val('');
      }
      selectedSetor = set;
      return $('select#idMicroAreaUnidade option, select#ItemVinc option').each(function() {
        var cnes, setor;
        setor = $(this).data('setor');
        if (!setor) {
          return;
        }
        cnes = setor.cnes;
        if (selectedSetor === cnes) {
          return $(this).removeAttr('disabled');
        } else {
          return $(this).attr('disabled', true);
        }
      });
    });
  });

  loadings = [];

  window.criaLoading = function(alvoID) {
    var boxCarregando, out;
    if (0 === $('#' + alvoID).length) {
      return;
    }
    out = 0 > loadings.indexOf(alvoID);
    if (out) {
      loadings.push(alvoID);
    }
    boxCarregando = '<div class="div-carregando" id="div-carregando-' + alvoID + '">';
    boxCarregando += '<div class="div-carregando-fundo"></div>';
    boxCarregando += '<div class="div-carregando-conteudo">';
    boxCarregando += '<img src="' + appPath + '../img/ajax-loader-2.gif" /><br>';
    boxCarregando += '<span><b>Carregando...</b></span>';
    boxCarregando += '</div>';
    boxCarregando += '</div>';
    if ($('#div-carregando-' + alvoID).length === 0) {
      $('body').append(boxCarregando);
    }
    $('#div-carregando-' + alvoID).css({
      display: 'block',
      width: $('#' + alvoID).css("width"),
      height: $('#' + alvoID).css("height"),
      top: $('#' + alvoID).offset().top,
      left: $('#' + alvoID).offset().left
    });
  };

  window.destroiLoading = function(alvoID) {
    var a, b;
    a = $.extend([], [], loadings);
    b = a.splice(a.indexOf(alvoID));
    b.shift();
    a = [].concat(a, b);
    loadings = a;
    return $('#div-carregando-' + alvoID).remove();
  };

  $(window).on('resize', function() {
    var alvoID, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = loadings.length; _i < _len; _i++) {
      alvoID = loadings[_i];
      _results.push($('#div-carregando-' + alvoID).css({
        width: 0,
        height: 0,
        top: $('#' + alvoID).offset().top,
        left: $('#' + alvoID).offset().left
      }).css({
        width: $('#' + alvoID).css("width"),
        height: $('#' + alvoID).css("height"),
        top: $('#' + alvoID).offset().top,
        left: $('#' + alvoID).offset().left
      }));
    }
    return _results;
  });

}).call(this);
