//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMIA_Objetivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACADEMIA_Objetivos()
        {
            this.ACADEMIA_FichaTreino = new HashSet<ACADEMIA_FichaTreino>();
        }
    
        public int NumContrato { get; set; }
        public int CodObjetivo { get; set; }
        public string DesObjetivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACADEMIA_FichaTreino> ACADEMIA_FichaTreino { get; set; }
    }
}
