//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMIA_FichaTreino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACADEMIA_FichaTreino()
        {
            this.ACADEMIA_FichaTreinoMetodo = new HashSet<ACADEMIA_FichaTreinoMetodo>();
            this.ACADEMIA_FichaTreinoExer = new HashSet<ACADEMIA_FichaTreinoExer>();
        }
    
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int ItemFicha { get; set; }
        public Nullable<int> CodObjetivo { get; set; }
        public Nullable<System.DateTime> DtFicha { get; set; }
        public Nullable<int> Frequencia { get; set; }
        public Nullable<System.DateTime> DtValidade { get; set; }
        public Nullable<int> CodProfissional { get; set; }
    
        public virtual ACADEMIA_Objetivos ACADEMIA_Objetivos { get; set; }
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACADEMIA_FichaTreinoMetodo> ACADEMIA_FichaTreinoMetodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACADEMIA_FichaTreinoExer> ACADEMIA_FichaTreinoExer { get; set; }
    }
}
