//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_Intinerarios
    {
        public int NumContrato { get; set; }
        public int NumIntinerario { get; set; }
        public string DesIntinerario { get; set; }
        public Nullable<decimal> Distancia { get; set; }
        public Nullable<int> TempoMedio { get; set; }
        public Nullable<int> NumParadas { get; set; }
        public string CEPOrigem { get; set; }
        public string EndeOrigem { get; set; }
        public string NomeCidadeOrigem { get; set; }
        public string NumOrigem { get; set; }
        public string UFOrigem { get; set; }
        public string BairroOrigem { get; set; }
        public string PontoRefOrigem { get; set; }
        public string LatitudeOrigem { get; set; }
        public string LongitudeOrigem { get; set; }
        public string CEPDestino { get; set; }
        public string EndeDestino { get; set; }
        public string NomeCidadeDestino { get; set; }
        public string NumDestino { get; set; }
        public string BairroDestino { get; set; }
        public string UFDestino { get; set; }
        public string PontoRefDestino { get; set; }
        public string LatitudeDestino { get; set; }
        public string LongitudeDestino { get; set; }
    }
}
