//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_MovimentaFrete
    {
        public int NumContrato { get; set; }
        public int AnoMov { get; set; }
        public decimal NumMov { get; set; }
        public string Placa { get; set; }
        public Nullable<int> CodMotorista { get; set; }
        public Nullable<decimal> Distancia { get; set; }
        public Nullable<decimal> VlrFrete { get; set; }
        public string Lacres { get; set; }
        public string Fatura { get; set; }
        public Nullable<decimal> QtdVol { get; set; }
        public string Especies { get; set; }
        public string Marca { get; set; }
        public string NumVol { get; set; }
        public Nullable<decimal> PesoLiq { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
    
        public virtual AE_Motoristas AE_Motoristas { get; set; }
        public virtual AE_Movimenta AE_Movimenta { get; set; }
        public virtual AE_Veiculos AE_Veiculos { get; set; }
    }
}
