//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_MovimentaItemSaida
    {
        public int NumContrato { get; set; }
        public int AnoMov { get; set; }
        public decimal NumMov { get; set; }
        public int Item { get; set; }
        public Nullable<int> AnoMovSai { get; set; }
        public Nullable<decimal> QtdSai { get; set; }
        public Nullable<decimal> NumMovSai { get; set; }
        public Nullable<int> ItemSai { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
    
        public virtual AE_MovimentaItem AE_MovimentaItem { get; set; }
    }
}
