//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_Movimenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AE_Movimenta()
        {
            this.AE_MovimentaItem = new HashSet<AE_MovimentaItem>();
        }
    
        public int NumContrato { get; set; }
        public int AnoMov { get; set; }
        public decimal NumMov { get; set; }
        public Nullable<int> CodTpDoc { get; set; }
        public Nullable<int> CodNatOper { get; set; }
        public Nullable<int> CodCondPag { get; set; }
        public string TipoMov { get; set; }
        public Nullable<int> CodTab { get; set; }
        public Nullable<int> CodTpEntrega { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> DtMov { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<int> CodSetor { get; set; }
        public Nullable<System.DateTime> DtDoc { get; set; }
        public string NumDoc { get; set; }
        public string Serie { get; set; }
        public string IdNfe { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public Nullable<int> CodSistema { get; set; }
        public string Obs { get; set; }
    
        public virtual AF_TipoDoc AF_TipoDoc { get; set; }
        public virtual AE_TpEntrega AE_TpEntrega { get; set; }
        public virtual AF_NatOperacao AF_NatOperacao { get; set; }
        public virtual AE_MovimentaCad AE_MovimentaCad { get; set; }
        public virtual AE_MovimentaCancel AE_MovimentaCancel { get; set; }
        public virtual AE_MovimentaFrete AE_MovimentaFrete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AE_MovimentaItem> AE_MovimentaItem { get; set; }
        public virtual AE_MovimentaSetor AE_MovimentaSetor { get; set; }
    }
}
