//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_MovimentaCad
    {
        public int NumContrato { get; set; }
        public int AnoMov { get; set; }
        public decimal NumMov { get; set; }
        public decimal Codigo { get; set; }
        public Nullable<decimal> VlrTotProd { get; set; }
        public Nullable<decimal> VlrTotDes { get; set; }
        public Nullable<decimal> VlrTotAcre { get; set; }
        public Nullable<decimal> VlrTotNota { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string ObsMov { get; set; }
        public Nullable<int> CodCredReq { get; set; }
        public string CodCID { get; set; }
        public string NomeRequisitante { get; set; }
        public Nullable<int> Retirada { get; set; }
    
        public virtual AE_Movimenta AE_Movimenta { get; set; }
    }
}
