//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_MotoristaSit
    {
        public int NumContrato { get; set; }
        public int CodMotorista { get; set; }
        public int ItemSit { get; set; }
        public Nullable<System.DateTime> DtSitMot { get; set; }
        public Nullable<int> CodSitFun { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
    
        public virtual AE_Motoristas AE_Motoristas { get; set; }
    }
}
