//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_ProdCusto
    {
        public int NumContrato { get; set; }
        public int CodProd { get; set; }
        public int CodCusto { get; set; }
        public string TipoCusto { get; set; }
        public Nullable<decimal> RefCusto { get; set; }
    
        public virtual AE_Custos AE_Custos { get; set; }
        public virtual AE_Produtos AE_Produtos { get; set; }
    }
}
