//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_ProdCaract
    {
        public int NumContrato { get; set; }
        public int CodProd { get; set; }
        public int CodCaract { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string Obs { get; set; }
    
        public virtual AE_Caracteristicas AE_Caracteristicas { get; set; }
        public virtual AE_Produtos AE_Produtos { get; set; }
    }
}
