//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_ProdTabela
    {
        public int NumContrato { get; set; }
        public int CodProd { get; set; }
        public int CodTab { get; set; }
        public int CodComp { get; set; }
        public System.DateTime Data { get; set; }
        public string CodMoeda { get; set; }
        public string CodProdTab { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> VlrMinimo { get; set; }
    
        public virtual AE_Composicao AE_Composicao { get; set; }
        public virtual AE_Tabelas AE_Tabelas { get; set; }
        public virtual AE_Produtos AE_Produtos { get; set; }
    }
}
