//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_Tabelas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AE_Tabelas()
        {
            this.AE_ProdTabela = new HashSet<AE_ProdTabela>();
            this.AS_ConvTab = new HashSet<AS_ConvTab>();
            this.AS_TabelaProc = new HashSet<AS_TabelaProc>();
            this.AS_TpGuiaItem = new HashSet<AS_TpGuiaItem>();
            this.AS_TpGuiaItemPad = new HashSet<AS_TpGuiaItemPad>();
        }
    
        public int CodTab { get; set; }
        public int NumContrato { get; set; }
        public string DesTab { get; set; }
        public Nullable<int> CodTISS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AE_ProdTabela> AE_ProdTabela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ConvTab> AS_ConvTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TabelaProc> AS_TabelaProc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TpGuiaItem> AS_TpGuiaItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TpGuiaItemPad> AS_TpGuiaItemPad { get; set; }
    }
}
