//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_ViagensData
    {
        public int NumContrato { get; set; }
        public int AnoViagem { get; set; }
        public decimal NumViagem { get; set; }
        public int ItemV { get; set; }
        public string Tipo { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Hora { get; set; }
        public Nullable<decimal> Kilometragem { get; set; }
    
        public virtual AE_Veiculos AE_Veiculos { get; set; }
        public virtual AE_Viagens AE_Viagens { get; set; }
    }
}
