//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_ViagensPassageiro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AE_ViagensPassageiro()
        {
            this.AE_ViagensAgendaAtend = new HashSet<AE_ViagensAgendaAtend>();
        }
    
        public int NumContrato { get; set; }
        public int AnoViagem { get; set; }
        public decimal NumViagem { get; set; }
        public int ItemPas { get; set; }
        public Nullable<int> NumFuncao { get; set; }
        public Nullable<int> CodDestino { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public string ObsPass { get; set; }
        public string Maca { get; set; }
    
        public virtual AE_Viagens AE_Viagens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AE_ViagensAgendaAtend> AE_ViagensAgendaAtend { get; set; }
        public virtual AE_ViagensFuncoes AE_ViagensFuncoes { get; set; }
    }
}
