//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_Bancos()
        {
            this.AF_ChequesRec = new HashSet<AF_ChequesRec>();
            this.AF_Contas = new HashSet<AF_Contas>();
        }
    
        public int NumContrato { get; set; }
        public string CodBanco { get; set; }
        public string NomeBanco { get; set; }
        public string DigBanco { get; set; }
        public string Logo { get; set; }
        public Nullable<int> LogoTam { get; set; }
        public Nullable<int> LogoAlt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_ChequesRec> AF_ChequesRec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_Contas> AF_Contas { get; set; }
    }
}
