//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_ContaCad
    {
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int AnoLan { get; set; }
        public decimal NumLan { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
    
        public virtual AF_Lancamentos AF_Lancamentos { get; set; }
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
    }
}
