//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_CondPag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_CondPag()
        {
            this.AF_Receber = new HashSet<AF_Receber>();
        }
    
        public int NumContrato { get; set; }
        public int CodCondPag { get; set; }
        public string DesCondPag { get; set; }
        public string DiasCondPag { get; set; }
        public Nullable<decimal> JurosCond { get; set; }
        public string TipoJuros { get; set; }
        public Nullable<int> NFe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_Receber> AF_Receber { get; set; }
    }
}
