//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_ChequesEmi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_ChequesEmi()
        {
            this.AF_ChequesEmiSit = new HashSet<AF_ChequesEmiSit>();
            this.AF_PagaCheques = new HashSet<AF_PagaCheques>();
        }
    
        public int NumContrato { get; set; }
        public int CodConta { get; set; }
        public string NumCheque { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string CodMoeda { get; set; }
        public Nullable<System.DateTime> DtCheque { get; set; }
        public Nullable<int> CodUsu { get; set; }
    
        public virtual AF_Contas AF_Contas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_ChequesEmiSit> AF_ChequesEmiSit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_PagaCheques> AF_PagaCheques { get; set; }
    }
}
