//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_CobrancaRet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_CobrancaRet()
        {
            this.AF_CobrancaRetReg = new HashSet<AF_CobrancaRetReg>();
        }
    
        public int NumContrato { get; set; }
        public int AnoRetorno { get; set; }
        public int NumRetorno { get; set; }
        public string NomeArquivo { get; set; }
        public Nullable<System.DateTime> DtArquivo { get; set; }
        public string CodBanco { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_CobrancaRetReg> AF_CobrancaRetReg { get; set; }
    }
}
