//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_FolhaPag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_FolhaPag()
        {
            this.AF_FolhaPagArq = new HashSet<AF_FolhaPagArq>();
            this.AF_FolhaPagCred = new HashSet<AF_FolhaPagCred>();
        }
    
        public int NumContrato { get; set; }
        public int AnoFol { get; set; }
        public int NumFol { get; set; }
        public Nullable<System.DateTime> DtProc { get; set; }
        public Nullable<int> CodSetor { get; set; }
        public Nullable<System.DateTime> DtFecha { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string Referencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_FolhaPagArq> AF_FolhaPagArq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_FolhaPagCred> AF_FolhaPagCred { get; set; }
    }
}
