//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_NatOperacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_NatOperacao()
        {
            this.AE_Movimenta = new HashSet<AE_Movimenta>();
        }
    
        public int NumContrato { get; set; }
        public int CodNatOper { get; set; }
        public string DesNatOper { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Finalidade { get; set; }
        public Nullable<int> Classe { get; set; }
        public Nullable<int> Seq { get; set; }
        public string CodOpera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AE_Movimenta> AE_Movimenta { get; set; }
    }
}
