//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_PagamentosEve
    {
        public int NumContrato { get; set; }
        public int AnoPag { get; set; }
        public decimal NumPag { get; set; }
        public int NumParcela { get; set; }
        public int CodEve { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string CodMoeda { get; set; }
        public Nullable<int> Codusu { get; set; }
    
        public virtual AF_EveFinan AF_EveFinan { get; set; }
        public virtual AF_PagarDoc AF_PagarDoc { get; set; }
    }
}
