//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_PagarDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_PagarDoc()
        {
            this.AF_Pagamentos = new HashSet<AF_Pagamentos>();
            this.AF_PagamentosEve = new HashSet<AF_PagamentosEve>();
        }
    
        public int NumContrato { get; set; }
        public int AnoPag { get; set; }
        public decimal NumPag { get; set; }
        public int NumParcela { get; set; }
        public Nullable<System.DateTime> DtEmissao { get; set; }
        public Nullable<System.DateTime> DtVenc { get; set; }
        public Nullable<int> CodTpDoc { get; set; }
        public string NumDoc { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string CodMoeda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_Pagamentos> AF_Pagamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_PagamentosEve> AF_PagamentosEve { get; set; }
        public virtual AF_Pagar AF_Pagar { get; set; }
    }
}
