//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Pagamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_Pagamentos()
        {
            this.AF_PagaCheques = new HashSet<AF_PagaCheques>();
        }
    
        public int NumContrato { get; set; }
        public int AnoPag { get; set; }
        public decimal NumPag { get; set; }
        public int NumParcela { get; set; }
        public int Item { get; set; }
        public Nullable<int> CodEsp { get; set; }
        public int AnoLan { get; set; }
        public Nullable<decimal> VlrPago { get; set; }
        public decimal NumLan { get; set; }
        public Nullable<int> CodConta { get; set; }
        public string CodMoeda { get; set; }
        public Nullable<int> CodUsu { get; set; }
    
        public virtual AF_Lancamentos AF_Lancamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_PagaCheques> AF_PagaCheques { get; set; }
        public virtual AF_PagarDoc AF_PagarDoc { get; set; }
    }
}
