//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_RecibosOV
    {
        public int NumContrato { get; set; }
        public int AnoRecibo { get; set; }
        public decimal NumRecibo { get; set; }
        public int Item { get; set; }
        public Nullable<int> CodEsp { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> CodConta { get; set; }
    
        public virtual AF_Recibos AF_Recibos { get; set; }
    }
}
