//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Recibos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_Recibos()
        {
            this.AF_RecibosCE = new HashSet<AF_RecibosCE>();
            this.AF_RecibosCR = new HashSet<AF_RecibosCR>();
            this.AF_RecibosFat = new HashSet<AF_RecibosFat>();
            this.AF_RecibosLanca = new HashSet<AF_RecibosLanca>();
            this.AF_RecibosOV = new HashSet<AF_RecibosOV>();
        }
    
        public int NumContrato { get; set; }
        public int AnoRecibo { get; set; }
        public decimal NumRecibo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public Nullable<System.DateTime> DtRecibo { get; set; }
        public Nullable<int> CodConta { get; set; }
        public Nullable<decimal> ValorDoc { get; set; }
        public string CompHis { get; set; }
        public Nullable<decimal> ValorJuros { get; set; }
        public Nullable<decimal> ValorMulta { get; set; }
        public Nullable<decimal> ValorCorrecao { get; set; }
        public Nullable<decimal> ValorOutrosA { get; set; }
        public Nullable<decimal> ValorDesconto { get; set; }
        public Nullable<decimal> ValorDinheiro { get; set; }
        public Nullable<decimal> ValorCheque { get; set; }
        public Nullable<decimal> ValorOutros { get; set; }
        public Nullable<decimal> ValorContaCor { get; set; }
        public Nullable<decimal> Troco { get; set; }
        public string VinculaCC { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
        public string Fechado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_RecibosCE> AF_RecibosCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_RecibosCR> AF_RecibosCR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_RecibosFat> AF_RecibosFat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_RecibosLanca> AF_RecibosLanca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_RecibosOV> AF_RecibosOV { get; set; }
    }
}
