//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_SitCheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AF_SitCheque()
        {
            this.AF_ChequesEmiSit = new HashSet<AF_ChequesEmiSit>();
            this.AF_ChequesRecSit = new HashSet<AF_ChequesRecSit>();
        }
    
        public int NumContrato { get; set; }
        public int CodSitCheque { get; set; }
        public string DeSitCheque { get; set; }
        public string Status { get; set; }
        public string OperEmi { get; set; }
        public string OperEmiAnt { get; set; }
        public string OperRec { get; set; }
        public string OperRecAnt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_ChequesEmiSit> AF_ChequesEmiSit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_ChequesRecSit> AF_ChequesRecSit { get; set; }
    }
}
