//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalNoDomicilio
    {
        public System.Guid id_cadastro_domiciliar { get; set; }
        public int id_tp_animal { get; set; }
    
        public virtual CadastroDomiciliar CadastroDomiciliar { get; set; }
    }
}
