//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APL_LocalVotacaoSecao
    {
        public int NumContrato { get; set; }
        public int CodLocalVota { get; set; }
        public int Zona { get; set; }
        public int Secao { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
    
        public virtual APL_LocalVotacao APL_LocalVotacao { get; set; }
    }
}
