//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APL_ColigaPartidos
    {
        public int NumContrato { get; set; }
        public int CodEleicao { get; set; }
        public int CodColiga { get; set; }
        public int CodPartido { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
        public Nullable<int> CodUsu { get; set; }
    
        public virtual APL_Coligacoes APL_Coligacoes { get; set; }
        public virtual APL_Partidos APL_Partidos { get; set; }
        public virtual APL_Eleicao APL_Eleicao { get; set; }
    }
}
