//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APL_LocalVotacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APL_LocalVotacao()
        {
            this.APL_LocalVotacaoSecao = new HashSet<APL_LocalVotacaoSecao>();
        }
    
        public int NumContrato { get; set; }
        public int CodLocalVota { get; set; }
        public string CEPLocalVota { get; set; }
        public string DesLocalVota { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Municipio { get; set; }
        public string UF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APL_LocalVotacaoSecao> APL_LocalVotacaoSecao { get; set; }
    }
}
