//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARQ020
    {
        public int codope { get; set; }
        public string nomope { get; set; }
        public string depope { get; set; }
        public Nullable<int> libage { get; set; }
        public Nullable<int> nivope { get; set; }
        public string senope { get; set; }
        public Nullable<int> codcon { get; set; }
        public Nullable<int> TipCon { get; set; }
        public string endope { get; set; }
        public string baiope { get; set; }
        public string cidope { get; set; }
        public string estope { get; set; }
        public string cepope { get; set; }
        public Nullable<int> codocu { get; set; }
        public string crmope { get; set; }
        public Nullable<int> numbip { get; set; }
        public string fonbip { get; set; }
        public string fonres { get; set; }
        public string foncom { get; set; }
        public string foncel { get; set; }
        public Nullable<int> temate { get; set; }
        public Nullable<double> perbas { get; set; }
        public Nullable<double> pervis { get; set; }
        public Nullable<double> pera60 { get; set; }
        public string cpfope { get; set; }
        public Nullable<System.DateTime> ultger { get; set; }
        public string segfei { get; set; }
        public string terfei { get; set; }
        public string quafei { get; set; }
        public string quifei { get; set; }
        public string sexfei { get; set; }
        public string sabado { get; set; }
        public string doming { get; set; }
        public string initr1 { get; set; }
        public string initr2 { get; set; }
        public string initr3 { get; set; }
        public string initr4 { get; set; }
        public string initr5 { get; set; }
        public string initr6 { get; set; }
        public string initr7 { get; set; }
        public string fintr1 { get; set; }
        public string fintr2 { get; set; }
        public string fintr3 { get; set; }
        public string fintr4 { get; set; }
        public string fintr5 { get; set; }
        public string fintr6 { get; set; }
        public string fintr7 { get; set; }
        public string idesm1 { get; set; }
        public string idesm2 { get; set; }
        public string idesm3 { get; set; }
        public string idesm4 { get; set; }
        public string idesm5 { get; set; }
        public string idesm6 { get; set; }
        public string idesm7 { get; set; }
        public string fdesm1 { get; set; }
        public string fdesm2 { get; set; }
        public string fdesm3 { get; set; }
        public string fdesm4 { get; set; }
        public string fdesm5 { get; set; }
        public string fdesm6 { get; set; }
        public string fdesm7 { get; set; }
        public string idere1 { get; set; }
        public string idere2 { get; set; }
        public string idere3 { get; set; }
        public string idere4 { get; set; }
        public string idere5 { get; set; }
        public string idere6 { get; set; }
        public string idere7 { get; set; }
        public string fdere1 { get; set; }
        public string fdere2 { get; set; }
        public string fdere3 { get; set; }
        public string fdere4 { get; set; }
        public string fdere5 { get; set; }
        public string fdere6 { get; set; }
        public string fdere7 { get; set; }
        public string idest1 { get; set; }
        public string idest2 { get; set; }
        public string idest3 { get; set; }
        public string idest4 { get; set; }
        public string idest5 { get; set; }
        public string idest6 { get; set; }
        public string idest7 { get; set; }
        public string fdest1 { get; set; }
        public string fdest2 { get; set; }
        public string fdest3 { get; set; }
        public string fdest4 { get; set; }
        public string fdest5 { get; set; }
        public string fdest6 { get; set; }
        public string fdest7 { get; set; }
        public Nullable<int> nivlib { get; set; }
        public string stalib { get; set; }
        public Nullable<System.DateTime> DatPre { get; set; }
        public Nullable<int> CodPos { get; set; }
        public string TemCor { get; set; }
        public string CodCbo { get; set; }
        public Nullable<int> UsoSup { get; set; }
        public string NumMat { get; set; }
        public Nullable<int> CodUni { get; set; }
        public Nullable<int> AviEve { get; set; }
        public Nullable<int> AviAge { get; set; }
        public Nullable<int> AviAni { get; set; }
        public Nullable<int> ALTINC { get; set; }
        public Nullable<int> TODATE { get; set; }
        public string CODEXP { get; set; }
        public Nullable<int> VISLIB { get; set; }
        public string ds_NomeAbreviado { get; set; }
        public string ds_Cargo { get; set; }
        public string ds_Documento { get; set; }
        public string ds_Especialidade { get; set; }
        public Nullable<int> fl_BaixaEstoque { get; set; }
        public Nullable<int> fl_InativaCadastro { get; set; }
        public Nullable<int> fl_AlteraProjeto { get; set; }
        public Nullable<int> cd_Setor { get; set; }
        public Nullable<int> cd_Perfil { get; set; }
        public string ds_CartaoSus { get; set; }
        public Nullable<int> fl_RetornaRequisicao { get; set; }
        public Nullable<int> fl_AutorizaRequisicao { get; set; }
        public Nullable<System.DateTime> dt_Alteracao { get; set; }
        public Nullable<int> fl_GuiaExame { get; set; }
        public Nullable<int> fl_PermissaoValidade { get; set; }
        public Nullable<int> fl_Ativo { get; set; }
        public Nullable<int> fl_GuiaEspecialidade { get; set; }
        public string ds_NumeroRG { get; set; }
        public Nullable<int> fl_ConselhoTutelar { get; set; }
        public Nullable<int> fl_BloqueiaDadosSociais { get; set; }
        public Nullable<int> fl_InclusaoGuiaEspecialidade { get; set; }
        public Nullable<int> fl_PermissaoCotaEspecialidade { get; set; }
        public Nullable<int> fl_ExcluirGuiaEspecialidade { get; set; }
        public Nullable<int> fl_VisualizarObs { get; set; }
        public Nullable<int> fl_ProjetoSaude { get; set; }
        public Nullable<int> fl_UPA { get; set; }
        public Nullable<int> fl_Encaminhamento { get; set; }
        public Nullable<int> fl_ManutencaoOdonto { get; set; }
        public Nullable<System.DateTime> dt_Nascimento { get; set; }
        public string ds_Sexo { get; set; }
        public string ds_NomeMae { get; set; }
        public string ds_Naturalidade { get; set; }
        public string ds_NaturalidadeUF { get; set; }
        public string ds_OrgaoEmissorRG { get; set; }
        public string ds_UFRG { get; set; }
        public Nullable<System.DateTime> dt_ExpedicaoRg { get; set; }
        public string ds_Nacionalidade { get; set; }
        public Nullable<System.DateTime> dt_EntradaPais { get; set; }
        public string ds_Escolaridade { get; set; }
        public string ds_OrgaoEmissorConselho { get; set; }
        public string ds_OrgaoEmissorConselhoUF { get; set; }
        public string fl_PermiteInclusao { get; set; }
        public string fl_PermiteAlteracao { get; set; }
        public string fl_PermiteExclusao { get; set; }
    }
}
