//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ArquivoFechaI
    {
        public int NumContrato { get; set; }
        public int NumArqFecha { get; set; }
        public string CNSProf { get; set; }
        public int AnoAtend { get; set; }
        public decimal NumAtend { get; set; }
        public string CBOProf { get; set; }
        public int Folha { get; set; }
        public int ItemF { get; set; }
        public int Seq { get; set; }
        public string CNSPaciente { get; set; }
        public string NomePaciente { get; set; }
        public string DtNasc { get; set; }
        public string IBGE { get; set; }
        public string Sexo { get; set; }
        public string DtAtend { get; set; }
        public string Procedimento { get; set; }
        public string Idade { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public string CID { get; set; }
        public string CarAtend { get; set; }
        public string RacaCor { get; set; }
        public string NumAut { get; set; }
    
        public virtual AS_ArquivoFecha AS_ArquivoFecha { get; set; }
    }
}
