//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_AtendColeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_AtendColeta()
        {
            this.AS_AtendColetaResul = new HashSet<AS_AtendColetaResul>();
        }
    
        public int NumContrato { get; set; }
        public int AnoAtend { get; set; }
        public decimal NumAtend { get; set; }
        public int ItemC { get; set; }
        public Nullable<int> CodMatExa { get; set; }
        public Nullable<System.DateTime> DtColeta { get; set; }
        public Nullable<System.DateTime> DtEncaminha { get; set; }
        public Nullable<int> CodLocEnc { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
    
        public virtual ASSMED_MatExames ASSMED_MatExames { get; set; }
        public virtual AS_Atendimento AS_Atendimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_AtendColetaResul> AS_AtendColetaResul { get; set; }
    }
}
