//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_AtendHist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_AtendHist()
        {
            this.AS_AtendReqExa = new HashSet<AS_AtendReqExa>();
        }
    
        public int NumContrato { get; set; }
        public int AnoAtend { get; set; }
        public decimal NumAtend { get; set; }
        public int ItemH { get; set; }
        public Nullable<int> CodParAtend { get; set; }
        public Nullable<System.DateTime> DtHist { get; set; }
        public string HrHist { get; set; }
        public string TextoHist { get; set; }
        public Nullable<decimal> Ref1Hist { get; set; }
        public Nullable<decimal> Ref2Hist { get; set; }
        public string CodCID { get; set; }
        public Nullable<int> CodCred { get; set; }
        public Nullable<int> CodLauPad { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string CertNome { get; set; }
        public string MD5 { get; set; }
        public Nullable<int> CodQuest { get; set; }
        public Nullable<int> ItemCadQuest { get; set; }
    
        public virtual AS_ParamAtend AS_ParamAtend { get; set; }
        public virtual AS_Atendimento AS_Atendimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_AtendReqExa> AS_AtendReqExa { get; set; }
    }
}
