//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_AtendAnexo
    {
        public int NumContrato { get; set; }
        public int AnoAtend { get; set; }
        public decimal NumAtend { get; set; }
        public int ItemAnexo { get; set; }
        public string NomeArquivo { get; set; }
        public int CodUsu { get; set; }
        public string NumIP { get; set; }
        public System.DateTime DtSistema { get; set; }
        public string DescAnexo { get; set; }
    }
}
