//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ArquivoFechaC
    {
        public int NumContrato { get; set; }
        public int NumArqFecha { get; set; }
        public string CBO { get; set; }
        public string Procedimento { get; set; }
        public string Idade { get; set; }
        public Nullable<decimal> Qtd { get; set; }
    
        public virtual AS_ArquivoFecha AS_ArquivoFecha { get; set; }
    }
}
