//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_AtendSolInt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_AtendSolInt()
        {
            this.AS_AtendSolIntProc = new HashSet<AS_AtendSolIntProc>();
        }
    
        public int NumContrato { get; set; }
        public int AnoAtend { get; set; }
        public decimal NumAtend { get; set; }
        public int ItemSolInt { get; set; }
        public Nullable<decimal> NumAtendSolInt { get; set; }
        public Nullable<int> AnoAtendSolInt { get; set; }
        public Nullable<System.DateTime> DtSugerida { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
        public Nullable<int> CodHospital { get; set; }
    
        public virtual AS_Atendimento AS_Atendimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_AtendSolIntProc> AS_AtendSolIntProc { get; set; }
    }
}
