//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_AtendMsg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_AtendMsg()
        {
            this.AS_AtendMsgLib = new HashSet<AS_AtendMsgLib>();
        }
    
        public int NumContrato { get; set; }
        public int AnoAtend { get; set; }
        public decimal NumAtend { get; set; }
        public int ItemMsg { get; set; }
        public Nullable<int> CodMsg { get; set; }
        public Nullable<int> ItemO { get; set; }
        public string Origem { get; set; }
        public Nullable<System.DateTime> DtMsg { get; set; }
        public string ObsMsg { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string StatusMsg { get; set; }
    
        public virtual AS_Atendimento AS_Atendimento { get; set; }
        public virtual AS_Mensagens AS_Mensagens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_AtendMsgLib> AS_AtendMsgLib { get; set; }
    }
}
