//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_AtendSolMed
    {
        public int NumContrato { get; set; }
        public int AnoAtend { get; set; }
        public decimal NumAtend { get; set; }
        public int ItemSM { get; set; }
        public Nullable<decimal> CodProd { get; set; }
        public Nullable<decimal> QtdSol { get; set; }
        public Nullable<decimal> QtdRec { get; set; }
        public string Dosagem { get; set; }
        public string Obs { get; set; }
    
        public virtual AS_Atendimento AS_Atendimento { get; set; }
    }
}
