//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ConvTabPar
    {
        public int NumContrato { get; set; }
        public int CodConv { get; set; }
        public int ItemTab { get; set; }
        public int CodComp { get; set; }
        public int Ordem { get; set; }
        public string CodIniProc { get; set; }
        public string CodFimProc { get; set; }
        public string TpPartConv { get; set; }
        public string TpPartPaci { get; set; }
        public Nullable<decimal> RefConv { get; set; }
        public Nullable<decimal> RefPaci { get; set; }
        public string CodMoeConv { get; set; }
        public string CodMoePaci { get; set; }
        public Nullable<int> Validade { get; set; }
        public string TiposGuia { get; set; }
        public string TipoCred { get; set; }
        public Nullable<int> CodTpEquipe { get; set; }
        public Nullable<int> CodCompBase { get; set; }
        public Nullable<int> CodCompRegra { get; set; }
        public string CondicaoRegra { get; set; }
        public string CodMoeRegra { get; set; }
        public Nullable<decimal> RefRegra { get; set; }
        public string SubstituiBase { get; set; }
    
        public virtual AE_Composicao AE_Composicao { get; set; }
        public virtual AS_ConvTab AS_ConvTab { get; set; }
    }
}
