//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Convenios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_Convenios()
        {
            this.AS_ArquivoFecha = new HashSet<AS_ArquivoFecha>();
            this.AS_ConvAudita = new HashSet<AS_ConvAudita>();
            this.AS_ConvContrato = new HashSet<AS_ConvContrato>();
            this.AS_ConvTab = new HashSet<AS_ConvTab>();
            this.AS_LeitosFaturaTab = new HashSet<AS_LeitosFaturaTab>();
            this.AS_TpGuiaItem = new HashSet<AS_TpGuiaItem>();
            this.AS_TpGuiaItemPad = new HashSet<AS_TpGuiaItemPad>();
        }
    
        public int NumContrato { get; set; }
        public int CodConv { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumRegistro { get; set; }
        public string NomeConv { get; set; }
        public string ExigeCarteira { get; set; }
        public Nullable<int> TamLogo { get; set; }
        public Nullable<int> AltLogo { get; set; }
        public string Logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ArquivoFecha> AS_ArquivoFecha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ConvAudita> AS_ConvAudita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ConvContrato> AS_ConvContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ConvTab> AS_ConvTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_LeitosFaturaTab> AS_LeitosFaturaTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TpGuiaItem> AS_TpGuiaItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TpGuiaItemPad> AS_TpGuiaItemPad { get; set; }
    }
}
