//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ExamesAgendaST
    {
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int Item { get; set; }
        public string Status { get; set; }
        public int ItemST { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> CodSetor { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public Nullable<int> CodUsu { get; set; }
    
        public virtual AS_ExamesAgenda AS_ExamesAgenda { get; set; }
    }
}
