//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ExamesAgenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_ExamesAgenda()
        {
            this.AS_ExamesAgendaST = new HashSet<AS_ExamesAgendaST>();
        }
    
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int Item { get; set; }
        public Nullable<int> CodTpExame { get; set; }
        public Nullable<System.DateTime> DtSolicita { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string HrSolicita { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
        public string ObsAgEx { get; set; }
        public Nullable<int> CodSetor { get; set; }
        public string Prioridade { get; set; }
        public Nullable<int> CodNatProc { get; set; }
        public string Justificativa { get; set; }
        public string HPMA { get; set; }
        public string ExComp { get; set; }
        public string JustficUr { get; set; }
        public Nullable<int> CodCred { get; set; }
        public string CodCID { get; set; }
        public int Id { get; set; }
        public Nullable<int> Seq { get; set; }
        public string UtilizaTrans { get; set; }
        public string PontoReferen { get; set; }
        public string Acompanhante { get; set; }
        public Nullable<int> PrioriReg { get; set; }
        public string JustificReg { get; set; }
        public Nullable<System.DateTime> AuditoriaData { get; set; }
        public Nullable<int> IdLocAgend { get; set; }
        public Nullable<System.DateTime> DtHrConsulta { get; set; }
        public string Status { get; set; }
        public string NomeCredenciado { get; set; }
        public Nullable<int> quemRegulou { get; set; }
        public Nullable<int> quemAgendou { get; set; }
        public Nullable<System.DateTime> agendamentoData { get; set; }
        public Nullable<int> CodSetorOrigem { get; set; }
        public string OBSagendamento { get; set; }
        public Nullable<int> quemCancelou { get; set; }
        public Nullable<int> tipoCancelamento { get; set; }
        public Nullable<System.DateTime> CancelamentoData { get; set; }
        public string OBSCancelamento { get; set; }
        public Nullable<int> quemComunicou { get; set; }
        public string OBSComunicado { get; set; }
        public Nullable<System.DateTime> ComunicadoData { get; set; }
    
        public virtual AS_ExameAgendaDT AS_ExameAgendaDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ExamesAgendaST> AS_ExamesAgendaST { get; set; }
    }
}
