//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_FinanProc
    {
        public int NumContrato { get; set; }
        public int CodTpFinan { get; set; }
        public Nullable<int> CodComp { get; set; }
    
        public virtual AE_Composicao AE_Composicao { get; set; }
    }
}
