//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_LeitosFaturaTab
    {
        public int NumContrato { get; set; }
        public int CodLeiFat { get; set; }
        public int Item { get; set; }
        public Nullable<int> CodConv { get; set; }
        public string CodProcTab { get; set; }
        public Nullable<int> CodTab { get; set; }
        public Nullable<System.DateTime> DtInicio { get; set; }
        public Nullable<System.DateTime> DtFinal { get; set; }
    
        public virtual AS_Convenios AS_Convenios { get; set; }
        public virtual AS_LeitosFatura AS_LeitosFatura { get; set; }
    }
}
