//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ParamAtend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_ParamAtend()
        {
            this.AS_AtendHist = new HashSet<AS_AtendHist>();
        }
    
        public int NumContrato { get; set; }
        public int CodParAtend { get; set; }
        public string DesParAtend { get; set; }
        public string Tipo { get; set; }
        public string CID10 { get; set; }
        public string Editor { get; set; }
        public string TitPar1 { get; set; }
        public string TitPar2 { get; set; }
        public string Padrao { get; set; }
        public string Grafico { get; set; }
        public string TpGrafico { get; set; }
        public string ReqExame { get; set; }
        public string odontograma { get; set; }
        public Nullable<int> CodQuest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_AtendHist> AS_AtendHist { get; set; }
    }
}
