//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_SitEscala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_SitEscala()
        {
            this.AS_CredEscala = new HashSet<AS_CredEscala>();
        }
    
        public int NumContrato { get; set; }
        public int CodSitEsc { get; set; }
        public string DesSitEsc { get; set; }
        public string StatusSitEsc { get; set; }
        public string IconeSitEsc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_CredEscala> AS_CredEscala { get; set; }
    }
}
