//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_TpGuiaSetor
    {
        public int NumContrato { get; set; }
        public int CodTpGuia { get; set; }
        public int CodSetor { get; set; }
        public Nullable<int> CodUsu { get; set; }
    
        public virtual AS_TpGuia AS_TpGuia { get; set; }
        public virtual Setores Setores { get; set; }
    }
}
