//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_TipoAcidente
    {
        public int NumContrato { get; set; }
        public int CodTpAcidente { get; set; }
        public string DesTpAcidente { get; set; }
    }
}
