//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_TpGuia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AS_TpGuia()
        {
            this.AS_TpGuiaItem = new HashSet<AS_TpGuiaItem>();
            this.AS_TpGuiaItemPad = new HashSet<AS_TpGuiaItemPad>();
            this.AS_TpGuiaSetor = new HashSet<AS_TpGuiaSetor>();
        }
    
        public int NumContrato { get; set; }
        public int CodTpGuia { get; set; }
        public string DesTpGuia { get; set; }
        public string Classificacao { get; set; }
        public string ExigeReq { get; set; }
        public string ExigeCID { get; set; }
        public string ExigeCred { get; set; }
        public string Padrao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TpGuiaItem> AS_TpGuiaItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TpGuiaItemPad> AS_TpGuiaItemPad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_TpGuiaSetor> AS_TpGuiaSetor { get; set; }
    }
}
