//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_TabRefLabItens
    {
        public int NumContrato { get; set; }
        public int CodTabRef { get; set; }
        public string Sexo { get; set; }
        public int ItemRef { get; set; }
        public Nullable<int> IdadeI { get; set; }
        public Nullable<int> IdadeF { get; set; }
        public string Descri { get; set; }
    
        public virtual AS_TabRefLab AS_TabRefLab { get; set; }
    }
}
