//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_TabelaProcComp
    {
        public int NumContrato { get; set; }
        public decimal CodProc { get; set; }
        public int CodTab { get; set; }
        public int CodComp { get; set; }
        public System.DateTime DtItem { get; set; }
        public Nullable<decimal> RefVlr { get; set; }
        public string CodMoeda { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<bool> CfgFechamento { get; set; }
    
        public virtual AE_Composicao AE_Composicao { get; set; }
        public virtual AS_TabelaProc AS_TabelaProc { get; set; }
    }
}
