//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_TabelasSUS
    {
        public int NumContrato { get; set; }
        public System.DateTime DtAtualizacao { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public Nullable<int> CodTab { get; set; }
        public Nullable<int> CodTabProfissao { get; set; }
        public string tb_procedimentos { get; set; }
        public string rl_procedimento_modalidade { get; set; }
        public string rl_procedimento_registro { get; set; }
        public string tb_ocupacao { get; set; }
        public string rl_procedimento_ocupacao { get; set; }
        public string tb_cid { get; set; }
        public string rl_procedimento_cid { get; set; }
        public string tb_regra_condicionada { get; set; }
        public string tb_servico { get; set; }
        public string tb_servico_classificacao { get; set; }
        public string rl_procedimento_regra_cond { get; set; }
        public string rl_procedimento_servico { get; set; }
        public string rl_procedimento_detalhe { get; set; }
        public string tb_detalhe { get; set; }
    }
}
