//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_Acesso
    {
        public string EMail { get; set; }
        public System.DateTime DtAcesso { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string Validou { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSaida { get; set; }
        public string ASPSESSIONIDQASRTRQT { get; set; }
        public Nullable<System.DateTime> DtUltVer { get; set; }
    }
}
