//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_Questionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_Questionarios()
        {
            this.ASSMED_CadastroQuest = new HashSet<ASSMED_CadastroQuest>();
            this.ASSMED_QuestionariosPerguntas = new HashSet<ASSMED_QuestionariosPerguntas>();
        }
    
        public int NumContrato { get; set; }
        public int CodQuest { get; set; }
        public string DesQuest { get; set; }
        public Nullable<System.DateTime> DtQuest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_CadastroQuest> ASSMED_CadastroQuest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_QuestionariosPerguntas> ASSMED_QuestionariosPerguntas { get; set; }
    }
}
