//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_CadastroCertidoes
    {
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int CodTpcertidao { get; set; }
        public string Serventia { get; set; }
        public string Acervo { get; set; }
        public string Tipo { get; set; }
        public string Ano { get; set; }
        public string TipoLivro { get; set; }
        public string NumLivro { get; set; }
        public string NumFolha { get; set; }
        public string Termo { get; set; }
        public string DV { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual ASSMED_TipoCertidoes ASSMED_TipoCertidoes { get; set; }
    }
}
