//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_VacinaConfRel
    {
        public int NumContrato { get; set; }
        public int CodVacina { get; set; }
        public int ItemRel { get; set; }
        public string Sexo { get; set; }
        public string Gestante { get; set; }
        public Nullable<int> Linha { get; set; }
        public string TipoIdade { get; set; }
        public string Dose { get; set; }
        public Nullable<int> IdadeIni { get; set; }
        public Nullable<int> IdadeFim { get; set; }
    
        public virtual ASSMED_Vacinas ASSMED_Vacinas { get; set; }
    }
}
