//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_CursosTurmasAlunos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_CursosTurmasAlunos()
        {
            this.AF_ReceberCursos = new HashSet<AF_ReceberCursos>();
        }
    
        public int NumContrato { get; set; }
        public decimal NumCurso { get; set; }
        public decimal ItemCurso { get; set; }
        public decimal Codigo { get; set; }
        public Nullable<System.DateTime> DtMatricula { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_ReceberCursos> AF_ReceberCursos { get; set; }
        public virtual ASSMED_CursosTurmas ASSMED_CursosTurmas { get; set; }
    }
}
