//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_PesJuridica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_PesJuridica()
        {
            this.IMO_Imobiliaria = new HashSet<IMO_Imobiliaria>();
        }
    
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public string CNPJ { get; set; }
        public string RazaoSocial { get; set; }
        public string InscMunicipal { get; set; }
        public string InscEstadual { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMO_Imobiliaria> IMO_Imobiliaria { get; set; }
    }
}
