
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ASSMED_Endereco
{

    public int NumContrato { get; set; }

    public decimal Codigo { get; set; }

    public int ItemEnd { get; set; }

    public string CEP { get; set; }

    public string TipoEnd { get; set; }

    public string Corresp { get; set; }

    public string Logradouro { get; set; }

    public string Bairro { get; set; }

    public string Complemento { get; set; }

    public string NomeCidade { get; set; }

    public string UF { get; set; }

    public string Numero { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public Nullable<int> CodTpLogra { get; set; }

    public Nullable<int> CodCidade { get; set; }

    public Nullable<int> SEMNUMERO { get; set; }

    public string ENDREFERENCIA { get; set; }

    public string ENDAREA { get; set; }

    public string ENDAREAMICRO { get; set; }

    public Nullable<int> ENDSEMAREA { get; set; }



    public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }

}

}
