//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_TurmaMatriculaSit
    {
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int ItemMat { get; set; }
        public int ItemSitMat { get; set; }
        public Nullable<int> CodSitMat { get; set; }
        public Nullable<System.DateTime> DtSitMat { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
    
        public virtual ASSMED_SituacaoMatricula ASSMED_SituacaoMatricula { get; set; }
        public virtual ASSMED_TurmaMatricula ASSMED_TurmaMatricula { get; set; }
    }
}
