//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_CadastroExamesBloqueados
    {
        public int id { get; set; }
        public Nullable<int> NumContrato { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public Nullable<int> qtdPerdoada { get; set; }
    }
}
