//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_CadastroQuest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_CadastroQuest()
        {
            this.ASSMED_CadastroQuestResp = new HashSet<ASSMED_CadastroQuestResp>();
        }
    
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int ItemCadQuest { get; set; }
        public Nullable<int> CodQuest { get; set; }
        public Nullable<int> CodSala { get; set; }
        public Nullable<decimal> CodProfissional { get; set; }
        public Nullable<System.DateTime> DtQuest { get; set; }
        public string HoraQuest { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string Obs { get; set; }
        public string NumIP { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual ASSMED_Cadastro ASSMED_Cadastro1 { get; set; }
        public virtual Setores Setores { get; set; }
        public virtual ASSMED_Questionarios ASSMED_Questionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_CadastroQuestResp> ASSMED_CadastroQuestResp { get; set; }
    }
}
