//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_VacinasValor
    {
        public int NumContrato { get; set; }
        public int CodVacina { get; set; }
        public int ItemVlr { get; set; }
        public Nullable<System.DateTime> DtVlr { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public Nullable<int> CodTab { get; set; }
        public Nullable<int> CodTpDoc { get; set; }
        public Nullable<int> CodCondPag { get; set; }
        public Nullable<int> CodOper { get; set; }
        public string TipoVlr { get; set; }
        public Nullable<int> DiaVenc { get; set; }
    
        public virtual ASSMED_Vacinas ASSMED_Vacinas { get; set; }
    }
}
