//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_CursosTurmas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_CursosTurmas()
        {
            this.ASSMED_CursosTurmasAlunos = new HashSet<ASSMED_CursosTurmasAlunos>();
            this.ASSMED_CursosTurmasHoras = new HashSet<ASSMED_CursosTurmasHoras>();
        }
    
        public int NumContrato { get; set; }
        public decimal NumCurso { get; set; }
        public decimal ItemCurso { get; set; }
        public Nullable<int> CodSala { get; set; }
        public Nullable<int> NumVagas { get; set; }
        public string CompCurso { get; set; }
        public Nullable<System.DateTime> DtInicio { get; set; }
        public Nullable<System.DateTime> DtFinal { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<decimal> CodProfissional { get; set; }
        public Nullable<decimal> ValorCurso { get; set; }
        public Nullable<int> CodCondPag { get; set; }
        public Nullable<int> CodTpDoc { get; set; }
        public Nullable<int> CodOper { get; set; }
    
        public virtual ASSMED_Cursos ASSMED_Cursos { get; set; }
        public virtual ASSMED_SALAS ASSMED_SALAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_CursosTurmasAlunos> ASSMED_CursosTurmasAlunos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_CursosTurmasHoras> ASSMED_CursosTurmasHoras { get; set; }
    }
}
