//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_TipoDocPessoal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_TipoDocPessoal()
        {
            this.ASSMED_CadastroDocPessoal = new HashSet<ASSMED_CadastroDocPessoal>();
        }
    
        public int NumContrato { get; set; }
        public int CodTpDocP { get; set; }
        public string DesTpDocP { get; set; }
        public string Numero { get; set; }
        public string Serie { get; set; }
        public string Secao { get; set; }
        public string Zona { get; set; }
        public string DtValidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_CadastroDocPessoal> ASSMED_CadastroDocPessoal { get; set; }
    }
}
