//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_PerguntaPadraoMult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_PerguntaPadraoMult()
        {
            this.ASSMED_PerguntaPadraoMulProx = new HashSet<ASSMED_PerguntaPadraoMulProx>();
        }
    
        public int NumContrato { get; set; }
        public int CodPergunta { get; set; }
        public int ItemMult { get; set; }
        public string DesMult { get; set; }
        public string Resposta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_PerguntaPadraoMulProx> ASSMED_PerguntaPadraoMulProx { get; set; }
        public virtual ASSMED_PerguntasPadrao ASSMED_PerguntasPadrao { get; set; }
    }
}
