//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_Programa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_Programa()
        {
            this.ASSMED_Abas = new HashSet<ASSMED_Abas>();
            this.ASSMED_ProgramaCampos = new HashSet<ASSMED_ProgramaCampos>();
            this.ASSMED_Sistema = new HashSet<ASSMED_Sistema>();
        }
    
        public string NomProg { get; set; }
        public string Descricao { get; set; }
        public string DesRes { get; set; }
        public string ProgGrava { get; set; }
        public string ProgExclui { get; set; }
        public string ProgPesquisa { get; set; }
        public string ProgLista { get; set; }
        public string ProgVoltar { get; set; }
        public string Imagem { get; set; }
        public string ProgForm { get; set; }
        public string ProgPai { get; set; }
        public string ProgCarrega { get; set; }
        public Nullable<int> ImgTam { get; set; }
        public Nullable<int> ImgAlt { get; set; }
        public string ProgVal { get; set; }
        public string Query { get; set; }
        public string NomeTabela { get; set; }
        public Nullable<int> TamanhoForm { get; set; }
        public Nullable<int> NumAba { get; set; }
        public string FormProcura { get; set; }
        public string QueryPai { get; set; }
        public string PaginaProcura { get; set; }
        public string OrientaLista { get; set; }
        public string BtInc { get; set; }
        public string BtExc { get; set; }
        public string BtPes { get; set; }
        public string BtGra { get; set; }
        public string BtLis { get; set; }
        public string BtEdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_Abas> ASSMED_Abas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_ProgramaCampos> ASSMED_ProgramaCampos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_Sistema> ASSMED_Sistema { get; set; }
    }
}
