//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_Usuario()
        {
            this.ASSMED_ContratoUsuario = new HashSet<ASSMED_ContratoUsuario>();
            this.Atendimento_Individual = new HashSet<Atendimento_Individual>();
        }
    
        public int CodUsu { get; set; }
        public string Login { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string Email { get; set; }
        public string NumIP { get; set; }
        public string CEP { get; set; }
        public string NomeCidade { get; set; }
        public string UF { get; set; }
        public string NumLog { get; set; }
        public Nullable<int> Ativo { get; set; }
        public string tipo_end { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string bairro { get; set; }
        public string municipio { get; set; }
        public string complemento { get; set; }
        public string fone { get; set; }
        public Nullable<int> id_user_cadastro { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<int> id_user_alteracao { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string cpf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_ContratoUsuario> ASSMED_ContratoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento_Individual> Atendimento_Individual { get; set; }
    }
}
