//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_Sistema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_Sistema()
        {
            this.ASSMED_SistemaUsuario = new HashSet<ASSMED_SistemaUsuario>();
            this.ASSMED_SistemaSecao = new HashSet<ASSMED_SistemaSecao>();
            this.grupo_Sistemas = new HashSet<grupo_Sistemas>();
            this.ASSMED_Programa = new HashSet<ASSMED_Programa>();
        }
    
        public int CodSistema { get; set; }
        public string Descrição { get; set; }
        public string DesMenu { get; set; }
        public string Imagem { get; set; }
        public Nullable<int> ImgTam { get; set; }
        public string ImagemI { get; set; }
        public Nullable<int> ImgAlt { get; set; }
        public string Icone { get; set; }
        public Nullable<int> IcoTam { get; set; }
        public Nullable<int> IcoAlt { get; set; }
        public string FaIcon { get; set; }
        public string BtnIcon { get; set; }
        public string Diretorio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_SistemaUsuario> ASSMED_SistemaUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_SistemaSecao> ASSMED_SistemaSecao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_Sistemas> grupo_Sistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_Programa> ASSMED_Programa { get; set; }
    }
}
