//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_SuporteAnda
    {
        public int AnoSuporte { get; set; }
        public decimal NumSuporte { get; set; }
        public int ItemSuporte { get; set; }
        public string EMailAtendente { get; set; }
        public string DescAtende { get; set; }
        public string Status { get; set; }
        public string EMailEncaminha { get; set; }
        public string NumIP { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string ArqAnexoAnda { get; set; }
    
        public virtual ASSMED_Suporte ASSMED_Suporte { get; set; }
    }
}
