//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_CadastroFoto
    {
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int ItemFoto { get; set; }
        public string PastaCli { get; set; }
        public string NomeArquivo { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
    }
}
