//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_SistemaUsuario
    {
        public int CodSistema { get; set; }
        public int CodUsu { get; set; }
        public int NumContrato { get; set; }
    
        public virtual ASSMED_Contratos ASSMED_Contratos { get; set; }
        public virtual ASSMED_Sistema ASSMED_Sistema { get; set; }
    }
}
