//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_Abas
    {
        public string NomProg { get; set; }
        public string ProgAba { get; set; }
        public Nullable<int> NumAba { get; set; }
        public Nullable<int> Ordem { get; set; }
        public Nullable<int> TamanhoAba { get; set; }
        public string ProgForm { get; set; }
        public string ProgJs { get; set; }
        public string FuncProcura { get; set; }
        public string Imagem { get; set; }
        public string ImagemI { get; set; }
        public Nullable<int> ImgTam { get; set; }
        public Nullable<int> ImgAlt { get; set; }
        public string ProgValida { get; set; }
    
        public virtual ASSMED_Programa ASSMED_Programa { get; set; }
    }
}
