//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_SistemaSecao
    {
        public int CodSistema { get; set; }
        public int NumSecao { get; set; }
        public string Janela { get; set; }
        public Nullable<int> Menu { get; set; }
        public Nullable<bool> exibeMenu { get; set; }
    
        public virtual ASSMED_Secao ASSMED_Secao { get; set; }
        public virtual ASSMED_Sistema ASSMED_Sistema { get; set; }
    }
}
