//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_SALASAgendaOcorrencia
    {
        public int CodSala { get; set; }
        public int NumContrato { get; set; }
        public System.DateTime Data { get; set; }
        public string Hora { get; set; }
        public int Ordem { get; set; }
        public int ItemOcorre { get; set; }
        public Nullable<System.DateTime> DtOcorrencia { get; set; }
        public string StatusAnterior { get; set; }
        public Nullable<decimal> CodAntes { get; set; }
        public string NomeAntes { get; set; }
        public string ObsAntes { get; set; }
        public Nullable<int> CodUsuAntes { get; set; }
        public string NumIPAntes { get; set; }
        public Nullable<System.DateTime> DtSistemaAntes { get; set; }
    
        public virtual ASSMED_SALASAgenda ASSMED_SALASAgenda { get; set; }
    }
}
