
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class ASSMED_CadastroDocPessoal
    {

    public int NumContrato { get; set; }

    public decimal Codigo { get; set; }

    public int CodTpDocP { get; set; }

    public Nullable<int> CodOrgao { get; set; }

    public string Numero { get; set; }

    public string Serie { get; set; }

    public string Secao { get; set; }

    public string Zona { get; set; }

    public Nullable<System.DateTime> DtEmissao { get; set; }

    public Nullable<System.DateTime> DtValidade { get; set; }

    public string UFOrgao { get; set; }

    public Nullable<int> CodUsu { get; set; }

    public Nullable<System.DateTime> DtSistema { get; set; }

    public string NumIP { get; set; }



    public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }

    }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

}
