//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_Profissionais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_Profissionais()
        {
            this.ASSMED_AvaliacaoFisica = new HashSet<ASSMED_AvaliacaoFisica>();
            this.ASSMED_CadastroVacina = new HashSet<ASSMED_CadastroVacina>();
            this.ASSMED_SALASPRESENCA = new HashSet<ASSMED_SALASPRESENCA>();
        }
    
        public int NumContrato { get; set; }
        public decimal CodProfissional { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public string NumRegistro { get; set; }
        public Nullable<int> NumConselho { get; set; }
        public string UFConselho { get; set; }
        public Nullable<System.DateTime> DtRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_AvaliacaoFisica> ASSMED_AvaliacaoFisica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_CadastroVacina> ASSMED_CadastroVacina { get; set; }
        public virtual ASSMED_PesFisica ASSMED_PesFisica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_SALASPRESENCA> ASSMED_SALASPRESENCA { get; set; }
    }
}
