//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_QuestionariosPerguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_QuestionariosPerguntas()
        {
            this.ASSMED_CadastroQuestResp = new HashSet<ASSMED_CadastroQuestResp>();
        }
    
        public int NumContrato { get; set; }
        public int CodQuest { get; set; }
        public int ItemQuest { get; set; }
        public Nullable<int> CodPergunta { get; set; }
        public Nullable<int> Ordem { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSMED_CadastroQuestResp> ASSMED_CadastroQuestResp { get; set; }
        public virtual ASSMED_PerguntasPadrao ASSMED_PerguntasPadrao { get; set; }
        public virtual ASSMED_Questionarios ASSMED_Questionarios { get; set; }
    }
}
