//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_VacinaSolicita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSMED_VacinaSolicita()
        {
            this.AF_ReceberVacina = new HashSet<AF_ReceberVacina>();
        }
    
        public int NumContrato { get; set; }
        public decimal Codigo { get; set; }
        public int ItemVacina { get; set; }
        public Nullable<int> CodVacina { get; set; }
        public Nullable<System.DateTime> DtSolicita { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<int> ItemVlr { get; set; }
        public string HrSolicita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AF_ReceberVacina> AF_ReceberVacina { get; set; }
        public virtual ASSMED_Vacinas ASSMED_Vacinas { get; set; }
    }
}
