//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSMED_CursosTurmasHoras
    {
        public int NumContrato { get; set; }
        public decimal NumCurso { get; set; }
        public decimal ItemCurso { get; set; }
        public int ItemDia { get; set; }
        public Nullable<int> DiaSemana { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFim { get; set; }
    
        public virtual ASSMED_CursosTurmas ASSMED_CursosTurmas { get; set; }
    }
}
