//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssRelCampos
    {
        public int NumRel { get; set; }
        public string NomeCampo { get; set; }
        public string TituloCampo { get; set; }
        public Nullable<int> Tamanho { get; set; }
        public Nullable<int> Ordem { get; set; }
        public Nullable<int> LinhaDet { get; set; }
        public string Soma { get; set; }
        public string Conta { get; set; }
        public string Automatico { get; set; }
        public string ValorFixo { get; set; }
    }
}
