//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento_Individual_Profissional_Saude
    {
        public long id { get; set; }
        public long id_atendimento_individual { get; set; }
        public decimal id_profissional_saude { get; set; }
        public int NumContrato { get; set; }
        public string cbo { get; set; }
        public string codibge_munic_nasc { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual Atendimento_Individual Atendimento_Individual { get; set; }
    }
}
