//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento_Individual_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atendimento_Individual_Usuario()
        {
            this.Atendimento_Individual_Exames = new HashSet<Atendimento_Individual_Exames>();
            this.SIGSM_Atendimento_Individual_Usuario_Condutas = new HashSet<SIGSM_Atendimento_Individual_Usuario_Condutas>();
        }
    
        public long id { get; set; }
        public string vacinacao_em_dia { get; set; }
        public Nullable<int> crianca_aleitamento_materno { get; set; }
        public Nullable<System.DateTime> gestante_dum { get; set; }
        public string gestante_gravidez_planejada { get; set; }
        public Nullable<int> gestante_idade_gestacional { get; set; }
        public Nullable<int> gestante_gestas_previas { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> altura { get; set; }
        public string modalidade_ad { get; set; }
        public Nullable<int> asma { get; set; }
        public Nullable<int> desnutricao { get; set; }
        public Nullable<int> diabetes { get; set; }
        public Nullable<int> dpoc { get; set; }
        public Nullable<int> hipertensao_arterial { get; set; }
        public Nullable<int> obesidade { get; set; }
        public Nullable<int> pre_natal { get; set; }
        public Nullable<int> puericultura { get; set; }
        public Nullable<int> puerperio { get; set; }
        public Nullable<int> saude_sexual_reprodutiva { get; set; }
        public Nullable<int> tabagismo { get; set; }
        public Nullable<int> usuario_alcool { get; set; }
        public Nullable<int> usuario_outras_drogas { get; set; }
        public Nullable<int> saude_mental { get; set; }
        public Nullable<int> reabilitacao { get; set; }
        public Nullable<int> tuberculose { get; set; }
        public Nullable<int> hanseniase { get; set; }
        public Nullable<int> dengue { get; set; }
        public Nullable<int> dst { get; set; }
        public Nullable<int> cancer_colo_utero { get; set; }
        public Nullable<int> cancer_mama { get; set; }
        public Nullable<int> risco_cardiovascular { get; set; }
        public string ciap2_01 { get; set; }
        public string ciap2_02 { get; set; }
        public string cid10_01 { get; set; }
        public string colesterol_total { get; set; }
        public string creatinina { get; set; }
        public string eas_equ { get; set; }
        public string eletrocardiograma { get; set; }
        public string eletroforese_de_hemoglobina { get; set; }
        public string espirometria { get; set; }
        public string exame_de_escarro { get; set; }
        public string glicemia { get; set; }
        public string hdl { get; set; }
        public string hemoglobina_glicada { get; set; }
        public string hemograma { get; set; }
        public string ldl { get; set; }
        public string retinografia_fundo_de_olho_com_oftalmologista { get; set; }
        public string sorologia_de_siflis_vdrl { get; set; }
        public string sorologia_para_dengue { get; set; }
        public string sorologia_para_hiv { get; set; }
        public string teste_indireto_de_antiglobulina_humana_tia { get; set; }
        public string teste_da_orelhinha { get; set; }
        public string teste_de_gravidez { get; set; }
        public string teste_do_olhinho { get; set; }
        public string teste_do_pezinho { get; set; }
        public string ultrassonografia_obstetrica { get; set; }
        public string urocultura { get; set; }
        public string outros_sia_chave { get; set; }
        public string outros_sia_valor { get; set; }
        public Nullable<int> pic { get; set; }
        public string ficou_em_observacao { get; set; }
        public Nullable<int> avaliacao_diagnostico { get; set; }
        public Nullable<int> procedimentos_clinicos_terapeuticos { get; set; }
        public Nullable<int> prescricao_terapeutica { get; set; }
        public Nullable<int> retorno_para_consulta_agendada { get; set; }
        public Nullable<int> retorno_para_cuidado_continuado_programado { get; set; }
        public Nullable<int> agendamento_para_grupos { get; set; }
        public Nullable<int> agendamento_para_nasf { get; set; }
        public Nullable<int> alta_do_episodio { get; set; }
        public Nullable<int> encaminhamento_interno_no_dia { get; set; }
        public Nullable<int> encaminhamento_para_servico_especializado { get; set; }
        public Nullable<int> encaminhamento_para_caps { get; set; }
        public Nullable<int> encaminhamento_para_internacao_hospitalar { get; set; }
        public Nullable<int> encaminhamento_para_urgencia { get; set; }
        public Nullable<int> encaminhamento_para_servico_de_atencao_domiciliar { get; set; }
        public Nullable<int> encaminhamento_intersetorial { get; set; }
        public long id_atendimento_individual { get; set; }
        public string numero_prontuario { get; set; }
        public Nullable<int> local_atendimento { get; set; }
        public string turno { get; set; }
        public Nullable<int> id_tipo_atendimento { get; set; }
        public Nullable<int> numero { get; set; }
        public string numero_cartao_sus { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string sexo { get; set; }
        public decimal id_identificacao_usuario { get; set; }
        public int NumContrato { get; set; }
        public Nullable<int> gestante_partos { get; set; }
        public string nome { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual Atendimento_Individual Atendimento_Individual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento_Individual_Exames> Atendimento_Individual_Exames { get; set; }
        public virtual Tipo_Atendimento Tipo_Atendimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Atendimento_Individual_Usuario_Condutas> SIGSM_Atendimento_Individual_Usuario_Condutas { get; set; }
    }
}
