//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento_Individual_Exames
    {
        public long id { get; set; }
        public Nullable<long> id_atendimento_usuario { get; set; }
        public Nullable<long> id_atendimento { get; set; }
        public string descricao { get; set; }
        public string solicitado { get; set; }
        public string avaliado { get; set; }
    
        public virtual Atendimento_Individual Atendimento_Individual { get; set; }
        public virtual Atendimento_Individual_Usuario Atendimento_Individual_Usuario { get; set; }
    }
}
