//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento_Individual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atendimento_Individual()
        {
            this.Atendimento_Individual_Exames = new HashSet<Atendimento_Individual_Exames>();
            this.Atendimento_Individual_Profissional_Saude = new HashSet<Atendimento_Individual_Profissional_Saude>();
            this.Atendimento_Individual_Usuario = new HashSet<Atendimento_Individual_Usuario>();
        }
    
        public long id { get; set; }
        public string digitado_por { get; set; }
        public System.DateTime data_entrada { get; set; }
        public string conferido_por { get; set; }
        public Nullable<long> numero_folha { get; set; }
        public Nullable<int> codigo_cnes_unidade { get; set; }
        public Nullable<int> codigo_equipe_ine { get; set; }
        public System.DateTime data_atendimento { get; set; }
        public bool enviado { get; set; }
        public Nullable<System.DateTime> data_envio { get; set; }
        public string usuario_envio { get; set; }
        public Nullable<int> id_status { get; set; }
        public string guid_esus { get; set; }
    
        public virtual ASSMED_Usuario ASSMED_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento_Individual_Exames> Atendimento_Individual_Exames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento_Individual_Profissional_Saude> Atendimento_Individual_Profissional_Saude { get; set; }
        public virtual SIGSM_Status SIGSM_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento_Individual_Usuario> Atendimento_Individual_Usuario { get; set; }
    }
}
