//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Autor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BB_Autor()
        {
            this.BB_AcervoAutor = new HashSet<BB_AcervoAutor>();
        }
    
        public int NumContrato { get; set; }
        public int CodAutor { get; set; }
        public string NomeAutor { get; set; }
        public string SobreAutor { get; set; }
        public string Email { get; set; }
        public string FotoAutor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_AcervoAutor> BB_AcervoAutor { get; set; }
    }
}
