//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_ListaEspera
    {
        public int NumContrato { get; set; }
        public decimal CodAcervo { get; set; }
        public int ItemEsp { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public Nullable<System.DateTime> DtLista { get; set; }
        public Nullable<System.DateTime> DtAtend { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIp { get; set; }
    
        public virtual BB_Acervo BB_Acervo { get; set; }
    }
}
