//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Situacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BB_Situacao()
        {
            this.BB_AcervoSit = new HashSet<BB_AcervoSit>();
        }
    
        public int NumContrato { get; set; }
        public int CodSitBB { get; set; }
        public string DesSitBB { get; set; }
        public string StatusBB { get; set; }
        public string TipoSit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_AcervoSit> BB_AcervoSit { get; set; }
    }
}
