//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEP_LOC
    {
        public string ID_LOCAL { get; set; }
        public string NM_LOCAL { get; set; }
        public string NR_CEP_LOCAL { get; set; }
        public string DS_TIPO_LOCAL { get; set; }
        public string FG_SIT_LOCAL { get; set; }
        public string DS_UF_LOCAL { get; set; }
        public int PK_LOC { get; set; }
        public int ID_PK_UF { get; set; }
    }
}
