//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatAuditoria
    {
        public int ID { get; set; }
        public Nullable<decimal> codigo { get; set; }
        public Nullable<int> item { get; set; }
        public string mensagem { get; set; }
        public Nullable<System.DateTime> datahora { get; set; }
        public Nullable<int> codUsu { get; set; }
        public Nullable<int> paraQuem { get; set; }
    }
}
