
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CondicoesDeSaude
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CondicoesDeSaude()
    {

        this.CadastroIndividual = new HashSet<CadastroIndividual>();

        this.DoencaCardiaca = new HashSet<DoencaCardiaca>();

        this.DoencaRespiratoria = new HashSet<DoencaRespiratoria>();

        this.DoencaRins = new HashSet<DoencaRins>();

    }


    public System.Guid id { get; set; }

    public string descricaoCausaInternacaoEm12Meses { get; set; }

    public string descricaoOutraCondicao1 { get; set; }

    public string descricaoOutraCondicao2 { get; set; }

    public string descricaoOutraCondicao3 { get; set; }

    public string descricaoPlantasMedicinaisUsadas { get; set; }

    public string maternidadeDeReferencia { get; set; }

    public Nullable<int> situacaoPeso { get; set; }

    public bool statusEhDependenteAlcool { get; set; }

    public bool statusEhDependenteOutrasDrogas { get; set; }

    public bool statusEhFumante { get; set; }

    public bool statusEhGestante { get; set; }

    public bool statusEstaAcamado { get; set; }

    public bool statusEstaDomiciliado { get; set; }

    public bool statusTemDiabetes { get; set; }

    public bool statusTemDoencaRespiratoria { get; set; }

    public bool statusTemHanseniase { get; set; }

    public bool statusTemHipertensaoArterial { get; set; }

    public bool statusTemTeveCancer { get; set; }

    public bool statusTemTeveDoencasRins { get; set; }

    public bool statusTemTuberculose { get; set; }

    public bool statusTeveAvcDerrame { get; set; }

    public bool statusTeveDoencaCardiaca { get; set; }

    public bool statusTeveInfarto { get; set; }

    public bool statusTeveInternadoem12Meses { get; set; }

    public bool statusUsaOutrasPraticasIntegrativasOuComplementares { get; set; }

    public bool statusUsaPlantasMedicinais { get; set; }

    public bool statusDiagnosticoMental { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CadastroIndividual> CadastroIndividual { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DoencaCardiaca> DoencaCardiaca { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DoencaRespiratoria> DoencaRespiratoria { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DoencaRins> DoencaRins { get; set; }

}

}
