//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DeficienciasCidadao
    {
        [Key]
        public System.Guid id_informacoes_socio_demograficas { get; set; }
        [Key]
        public int id_tp_deficiencia_cidadao { get; set; }
    
        public virtual InformacoesSocioDemograficas InformacoesSocioDemograficas { get; set; }
    }
}
