//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DomainContainer : DbContext
    {
        public DomainContainer()
            : base("name=DomainContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalNoDomicilio> AnimalNoDomicilio { get; set; }
        public virtual DbSet<CadastroDomiciliar> CadastroDomiciliar { get; set; }
        public virtual DbSet<CadastroIndividual> CadastroIndividual { get; set; }
        public virtual DbSet<CondicaoMoradia> CondicaoMoradia { get; set; }
        public virtual DbSet<CondicoesDeSaude> CondicoesDeSaude { get; set; }
        public virtual DbSet<DeficienciasCidadao> DeficienciasCidadao { get; set; }
        public virtual DbSet<DoencaCardiaca> DoencaCardiaca { get; set; }
        public virtual DbSet<DoencaRespiratoria> DoencaRespiratoria { get; set; }
        public virtual DbSet<DoencaRins> DoencaRins { get; set; }
        public virtual DbSet<EmSituacaoDeRua> EmSituacaoDeRua { get; set; }
        public virtual DbSet<EnderecoLocalPermanencia> EnderecoLocalPermanencia { get; set; }
        public virtual DbSet<FamiliaRow> FamiliaRow { get; set; }
        public virtual DbSet<FichaVisitaDomiciliarChild> FichaVisitaDomiciliarChild { get; set; }
        public virtual DbSet<FichaVisitaDomiciliarMaster> FichaVisitaDomiciliarMaster { get; set; }
        public virtual DbSet<HigienePessoalSituacaoRua> HigienePessoalSituacaoRua { get; set; }
        public virtual DbSet<IdentificacaoUsuarioCidadao> IdentificacaoUsuarioCidadao { get; set; }
        public virtual DbSet<InformacoesSocioDemograficas> InformacoesSocioDemograficas { get; set; }
        public virtual DbSet<InstituicaoPermanencia> InstituicaoPermanencia { get; set; }
        public virtual DbSet<OrigemAlimentoSituacaoRua> OrigemAlimentoSituacaoRua { get; set; }
        public virtual DbSet<OrigemVisita> OrigemVisita { get; set; }
        public virtual DbSet<ResponsavelPorCrianca> ResponsavelPorCrianca { get; set; }
        public virtual DbSet<SaidaCidadaoCadastro> SaidaCidadaoCadastro { get; set; }
        public virtual DbSet<UnicaLotacaoTransport> UnicaLotacaoTransport { get; set; }
        public virtual DbSet<ACADEMIA_Aparelhos> ACADEMIA_Aparelhos { get; set; }
        public virtual DbSet<ACADEMIA_Exercicios> ACADEMIA_Exercicios { get; set; }
        public virtual DbSet<ACADEMIA_FichaTreino> ACADEMIA_FichaTreino { get; set; }
        public virtual DbSet<ACADEMIA_FichaTreinoExer> ACADEMIA_FichaTreinoExer { get; set; }
        public virtual DbSet<ACADEMIA_FichaTreinoMetodo> ACADEMIA_FichaTreinoMetodo { get; set; }
        public virtual DbSet<ACADEMIA_GrupoMuscular> ACADEMIA_GrupoMuscular { get; set; }
        public virtual DbSet<ACADEMIA_Metodo> ACADEMIA_Metodo { get; set; }
        public virtual DbSet<ACADEMIA_Objetivos> ACADEMIA_Objetivos { get; set; }
        public virtual DbSet<AE_Caracteristicas> AE_Caracteristicas { get; set; }
        public virtual DbSet<AE_Categoria> AE_Categoria { get; set; }
        public virtual DbSet<AE_CategSistema> AE_CategSistema { get; set; }
        public virtual DbSet<AE_Composicao> AE_Composicao { get; set; }
        public virtual DbSet<AE_Custos> AE_Custos { get; set; }
        public virtual DbSet<AE_Embalagem> AE_Embalagem { get; set; }
        public virtual DbSet<AE_Intinerarios> AE_Intinerarios { get; set; }
        public virtual DbSet<AE_Marcas> AE_Marcas { get; set; }
        public virtual DbSet<AE_Moedas> AE_Moedas { get; set; }
        public virtual DbSet<AE_MoedasVlr> AE_MoedasVlr { get; set; }
        public virtual DbSet<AE_Motoristas> AE_Motoristas { get; set; }
        public virtual DbSet<AE_MotoristaSit> AE_MotoristaSit { get; set; }
        public virtual DbSet<AE_Movimenta> AE_Movimenta { get; set; }
        public virtual DbSet<AE_MovimentaCad> AE_MovimentaCad { get; set; }
        public virtual DbSet<AE_MovimentaCancel> AE_MovimentaCancel { get; set; }
        public virtual DbSet<AE_MovimentaFrete> AE_MovimentaFrete { get; set; }
        public virtual DbSet<AE_MovimentaItem> AE_MovimentaItem { get; set; }
        public virtual DbSet<AE_MovimentaItemSaida> AE_MovimentaItemSaida { get; set; }
        public virtual DbSet<AE_MovimentaSetor> AE_MovimentaSetor { get; set; }
        public virtual DbSet<AE_ProdCaract> AE_ProdCaract { get; set; }
        public virtual DbSet<AE_ProdCusto> AE_ProdCusto { get; set; }
        public virtual DbSet<AE_ProdEmbalagem> AE_ProdEmbalagem { get; set; }
        public virtual DbSet<AE_ProdFabrica> AE_ProdFabrica { get; set; }
        public virtual DbSet<AE_ProdTabela> AE_ProdTabela { get; set; }
        public virtual DbSet<AE_Produtos> AE_Produtos { get; set; }
        public virtual DbSet<AE_SitTrib> AE_SitTrib { get; set; }
        public virtual DbSet<AE_Tabelas> AE_Tabelas { get; set; }
        public virtual DbSet<AE_TipoReferencia> AE_TipoReferencia { get; set; }
        public virtual DbSet<AE_TpEntrega> AE_TpEntrega { get; set; }
        public virtual DbSet<AE_Unidades> AE_Unidades { get; set; }
        public virtual DbSet<AE_Veiculos> AE_Veiculos { get; set; }
        public virtual DbSet<AE_VeiculosAferi> AE_VeiculosAferi { get; set; }
        public virtual DbSet<AE_Viagens> AE_Viagens { get; set; }
        public virtual DbSet<AE_ViagensAgendaAtend> AE_ViagensAgendaAtend { get; set; }
        public virtual DbSet<AE_ViagensAgendamento> AE_ViagensAgendamento { get; set; }
        public virtual DbSet<AE_ViagensData> AE_ViagensData { get; set; }
        public virtual DbSet<AE_ViagensDestinos> AE_ViagensDestinos { get; set; }
        public virtual DbSet<AE_ViagensFuncoes> AE_ViagensFuncoes { get; set; }
        public virtual DbSet<AE_ViagensPassageiro> AE_ViagensPassageiro { get; set; }
        public virtual DbSet<AF_Bancos> AF_Bancos { get; set; }
        public virtual DbSet<AF_ChequesEmi> AF_ChequesEmi { get; set; }
        public virtual DbSet<AF_ChequesEmiSit> AF_ChequesEmiSit { get; set; }
        public virtual DbSet<AF_ChequesRec> AF_ChequesRec { get; set; }
        public virtual DbSet<AF_ChequesRecSit> AF_ChequesRecSit { get; set; }
        public virtual DbSet<AF_CobrancaRet> AF_CobrancaRet { get; set; }
        public virtual DbSet<AF_CobrancaRetReg> AF_CobrancaRetReg { get; set; }
        public virtual DbSet<AF_CondPag> AF_CondPag { get; set; }
        public virtual DbSet<AF_ContaCad> AF_ContaCad { get; set; }
        public virtual DbSet<AF_ContaCadSld> AF_ContaCadSld { get; set; }
        public virtual DbSet<AF_Contas> AF_Contas { get; set; }
        public virtual DbSet<AF_ContasMensagens> AF_ContasMensagens { get; set; }
        public virtual DbSet<AF_Especie> AF_Especie { get; set; }
        public virtual DbSet<AF_EveFinan> AF_EveFinan { get; set; }
        public virtual DbSet<AF_FolhaPag> AF_FolhaPag { get; set; }
        public virtual DbSet<AF_FolhaPagArq> AF_FolhaPagArq { get; set; }
        public virtual DbSet<AF_FolhaPagCred> AF_FolhaPagCred { get; set; }
        public virtual DbSet<AF_HistLanca> AF_HistLanca { get; set; }
        public virtual DbSet<AF_Lancamentos> AF_Lancamentos { get; set; }
        public virtual DbSet<AF_NatOperacao> AF_NatOperacao { get; set; }
        public virtual DbSet<AF_OperCont> AF_OperCont { get; set; }
        public virtual DbSet<AF_PagaCheques> AF_PagaCheques { get; set; }
        public virtual DbSet<AF_Pagamentos> AF_Pagamentos { get; set; }
        public virtual DbSet<AF_PagamentosEve> AF_PagamentosEve { get; set; }
        public virtual DbSet<AF_Pagar> AF_Pagar { get; set; }
        public virtual DbSet<AF_PagarDoc> AF_PagarDoc { get; set; }
        public virtual DbSet<AF_RecebeCheque> AF_RecebeCheque { get; set; }
        public virtual DbSet<AF_Receber> AF_Receber { get; set; }
        public virtual DbSet<AF_ReceberCursos> AF_ReceberCursos { get; set; }
        public virtual DbSet<AF_ReceberDoc> AF_ReceberDoc { get; set; }
        public virtual DbSet<AF_ReceberMatricula> AF_ReceberMatricula { get; set; }
        public virtual DbSet<AF_ReceberVacina> AF_ReceberVacina { get; set; }
        public virtual DbSet<AF_Recebimento> AF_Recebimento { get; set; }
        public virtual DbSet<AF_RecebimentoEve> AF_RecebimentoEve { get; set; }
        public virtual DbSet<AF_Recibos> AF_Recibos { get; set; }
        public virtual DbSet<AF_RecibosCE> AF_RecibosCE { get; set; }
        public virtual DbSet<AF_RecibosCR> AF_RecibosCR { get; set; }
        public virtual DbSet<AF_RecibosFat> AF_RecibosFat { get; set; }
        public virtual DbSet<AF_RecibosLanca> AF_RecibosLanca { get; set; }
        public virtual DbSet<AF_RecibosOV> AF_RecibosOV { get; set; }
        public virtual DbSet<AF_SitCheque> AF_SitCheque { get; set; }
        public virtual DbSet<AF_TipoDoc> AF_TipoDoc { get; set; }
        public virtual DbSet<AF_TipoDocCtrNum> AF_TipoDocCtrNum { get; set; }
        public virtual DbSet<APL_CadRegiao> APL_CadRegiao { get; set; }
        public virtual DbSet<APL_CadResp> APL_CadResp { get; set; }
        public virtual DbSet<APL_Candidato> APL_Candidato { get; set; }
        public virtual DbSet<APL_Coligacoes> APL_Coligacoes { get; set; }
        public virtual DbSet<APL_ColigaPartidos> APL_ColigaPartidos { get; set; }
        public virtual DbSet<APL_Coordenadores> APL_Coordenadores { get; set; }
        public virtual DbSet<APL_Eleicao> APL_Eleicao { get; set; }
        public virtual DbSet<APL_LocalVotacao> APL_LocalVotacao { get; set; }
        public virtual DbSet<APL_LocalVotacaoSecao> APL_LocalVotacaoSecao { get; set; }
        public virtual DbSet<APL_Partidos> APL_Partidos { get; set; }
        public virtual DbSet<APL_Pleito> APL_Pleito { get; set; }
        public virtual DbSet<APL_Regioes> APL_Regioes { get; set; }
        public virtual DbSet<APL_RegioesCoordenadas> APL_RegioesCoordenadas { get; set; }
        public virtual DbSet<APL_Solicitacoes> APL_Solicitacoes { get; set; }
        public virtual DbSet<APL_SolicitaDesp> APL_SolicitaDesp { get; set; }
        public virtual DbSet<APL_TpSolicitacoes> APL_TpSolicitacoes { get; set; }
        public virtual DbSet<AS_Acidente> AS_Acidente { get; set; }
        public virtual DbSet<AS_Acomodacoes> AS_Acomodacoes { get; set; }
        public virtual DbSet<AS_AcomodacoesCarac> AS_AcomodacoesCarac { get; set; }
        public virtual DbSet<AS_ArquivoFecha> AS_ArquivoFecha { get; set; }
        public virtual DbSet<AS_ArquivoFechaC> AS_ArquivoFechaC { get; set; }
        public virtual DbSet<AS_ArquivoFechaI> AS_ArquivoFechaI { get; set; }
        public virtual DbSet<AS_AtendAlta> AS_AtendAlta { get; set; }
        public virtual DbSet<AS_AtendAnexo> AS_AtendAnexo { get; set; }
        public virtual DbSet<AS_AtendCli> AS_AtendCli { get; set; }
        public virtual DbSet<AS_AtendColeta> AS_AtendColeta { get; set; }
        public virtual DbSet<AS_AtendColetaResul> AS_AtendColetaResul { get; set; }
        public virtual DbSet<AS_AtendDocumentos> AS_AtendDocumentos { get; set; }
        public virtual DbSet<AS_AtendHist> AS_AtendHist { get; set; }
        public virtual DbSet<AS_Atendimento> AS_Atendimento { get; set; }
        public virtual DbSet<AS_AtendInterna> AS_AtendInterna { get; set; }
        public virtual DbSet<AS_AtendItem> AS_AtendItem { get; set; }
        public virtual DbSet<AS_AtendItemEqp> AS_AtendItemEqp { get; set; }
        public virtual DbSet<AS_AtendItemFecha> AS_AtendItemFecha { get; set; }
        public virtual DbSet<AS_AtendItemProp> AS_AtendItemProp { get; set; }
        public virtual DbSet<AS_AtendItemValor> AS_AtendItemValor { get; set; }
        public virtual DbSet<AS_AtendLeito> AS_AtendLeito { get; set; }
        public virtual DbSet<AS_AtendMsg> AS_AtendMsg { get; set; }
        public virtual DbSet<AS_AtendMsgLib> AS_AtendMsgLib { get; set; }
        public virtual DbSet<AS_AtendReqExa> AS_AtendReqExa { get; set; }
        public virtual DbSet<AS_AtendReqSADT> AS_AtendReqSADT { get; set; }
        public virtual DbSet<AS_AtendSolInt> AS_AtendSolInt { get; set; }
        public virtual DbSet<AS_AtendSolIntProc> AS_AtendSolIntProc { get; set; }
        public virtual DbSet<AS_AtendSolMed> AS_AtendSolMed { get; set; }
        public virtual DbSet<AS_BrasIndice> AS_BrasIndice { get; set; }
        public virtual DbSet<AS_BrasIndiceArq> AS_BrasIndiceArq { get; set; }
        public virtual DbSet<AS_CaracLeito> AS_CaracLeito { get; set; }
        public virtual DbSet<AS_CaraterInt> AS_CaraterInt { get; set; }
        public virtual DbSet<AS_CID10> AS_CID10 { get; set; }
        public virtual DbSet<AS_ContPadrao> AS_ContPadrao { get; set; }
        public virtual DbSet<AS_ConvAudita> AS_ConvAudita { get; set; }
        public virtual DbSet<AS_ConvContrato> AS_ConvContrato { get; set; }
        public virtual DbSet<AS_Convenios> AS_Convenios { get; set; }
        public virtual DbSet<AS_ConvTab> AS_ConvTab { get; set; }
        public virtual DbSet<AS_ConvTabEqp> AS_ConvTabEqp { get; set; }
        public virtual DbSet<AS_ConvTabPar> AS_ConvTabPar { get; set; }
        public virtual DbSet<AS_CredAgenda> AS_CredAgenda { get; set; }
        public virtual DbSet<AS_Credenciados> AS_Credenciados { get; set; }
        public virtual DbSet<AS_CredenciadosUsu> AS_CredenciadosUsu { get; set; }
        public virtual DbSet<AS_CredenciadosVinc> AS_CredenciadosVinc { get; set; }
        public virtual DbSet<AS_CredEscala> AS_CredEscala { get; set; }
        public virtual DbSet<AS_CredEsp> AS_CredEsp { get; set; }
        public virtual DbSet<AS_Escolaridade> AS_Escolaridade { get; set; }
        public virtual DbSet<AS_EspAgenda> AS_EspAgenda { get; set; }
        public virtual DbSet<AS_Especialidades> AS_Especialidades { get; set; }
        public virtual DbSet<AS_EspecialidadesUsu> AS_EspecialidadesUsu { get; set; }
        public virtual DbSet<AS_ExameAgendaDT> AS_ExameAgendaDT { get; set; }
        public virtual DbSet<AS_EXAMES_LOCAGEND> AS_EXAMES_LOCAGEND { get; set; }
        public virtual DbSet<AS_ExamesAgenda> AS_ExamesAgenda { get; set; }
        public virtual DbSet<AS_EXAMESAGENDAPRIORIDADE> AS_EXAMESAGENDAPRIORIDADE { get; set; }
        public virtual DbSet<AS_ExamesAgendaST> AS_ExamesAgendaST { get; set; }
        public virtual DbSet<AS_FinanProc> AS_FinanProc { get; set; }
        public virtual DbSet<AS_FuncaoLeito> AS_FuncaoLeito { get; set; }
        public virtual DbSet<AS_Hierarquia> AS_Hierarquia { get; set; }
        public virtual DbSet<AS_LaudosPadrao> AS_LaudosPadrao { get; set; }
        public virtual DbSet<AS_Leitos> AS_Leitos { get; set; }
        public virtual DbSet<AS_LeitosCarac> AS_LeitosCarac { get; set; }
        public virtual DbSet<AS_LeitosFatura> AS_LeitosFatura { get; set; }
        public virtual DbSet<AS_LeitosFaturaTab> AS_LeitosFaturaTab { get; set; }
        public virtual DbSet<AS_LeitosFuncao> AS_LeitosFuncao { get; set; }
        public virtual DbSet<AS_MeioLocomocao> AS_MeioLocomocao { get; set; }
        public virtual DbSet<AS_Mensagens> AS_Mensagens { get; set; }
        public virtual DbSet<AS_MovimentaAtend> AS_MovimentaAtend { get; set; }
        public virtual DbSet<AS_NACIONALIDADE> AS_NACIONALIDADE { get; set; }
        public virtual DbSet<AS_NatProcura> AS_NatProcura { get; set; }
        public virtual DbSet<AS_ParamAtend> AS_ParamAtend { get; set; }
        public virtual DbSet<AS_Procedimentos> AS_Procedimentos { get; set; }
        public virtual DbSet<AS_Profissoes> AS_Profissoes { get; set; }
        public virtual DbSet<AS_ProfissoesTab> AS_ProfissoesTab { get; set; }
        public virtual DbSet<AS_RacaCor> AS_RacaCor { get; set; }
        public virtual DbSet<AS_RetTributos> AS_RetTributos { get; set; }
        public virtual DbSet<AS_SetoresAgenda> AS_SetoresAgenda { get; set; }
        public virtual DbSet<AS_SetoresPar> AS_SetoresPar { get; set; }
        public virtual DbSet<AS_SIABRegioes> AS_SIABRegioes { get; set; }
        public virtual DbSet<AS_SitEscala> AS_SitEscala { get; set; }
        public virtual DbSet<AS_TabelaProc> AS_TabelaProc { get; set; }
        public virtual DbSet<AS_TabelaProcAud> AS_TabelaProcAud { get; set; }
        public virtual DbSet<AS_TabelaProcCID> AS_TabelaProcCID { get; set; }
        public virtual DbSet<AS_TabelaProcComp> AS_TabelaProcComp { get; set; }
        public virtual DbSet<AS_TabelaProcProf> AS_TabelaProcProf { get; set; }
        public virtual DbSet<AS_TabelasSUS> AS_TabelasSUS { get; set; }
        public virtual DbSet<AS_TabProfissao> AS_TabProfissao { get; set; }
        public virtual DbSet<AS_TabRefLab> AS_TabRefLab { get; set; }
        public virtual DbSet<AS_TabRefLabItens> AS_TabRefLabItens { get; set; }
        public virtual DbSet<AS_TipoAcidente> AS_TipoAcidente { get; set; }
        public virtual DbSet<AS_TipoAcomoda> AS_TipoAcomoda { get; set; }
        public virtual DbSet<AS_TipoAlta> AS_TipoAlta { get; set; }
        public virtual DbSet<AS_tipoAtend> AS_tipoAtend { get; set; }
        public virtual DbSet<AS_TipoEquipe> AS_TipoEquipe { get; set; }
        public virtual DbSet<AS_TipoExames> AS_TipoExames { get; set; }
        public virtual DbSet<as_tipoExames_valores> as_tipoExames_valores { get; set; }
        public virtual DbSet<AS_TipoExamesCota> AS_TipoExamesCota { get; set; }
        public virtual DbSet<AS_TipoExamesEsp> AS_TipoExamesEsp { get; set; }
        public virtual DbSet<AS_TipoInterna> AS_TipoInterna { get; set; }
        public virtual DbSet<AS_TipoUnidade> AS_TipoUnidade { get; set; }
        public virtual DbSet<AS_TpGuia> AS_TpGuia { get; set; }
        public virtual DbSet<AS_TpGuiaItem> AS_TpGuiaItem { get; set; }
        public virtual DbSet<AS_TpGuiaItemPad> AS_TpGuiaItemPad { get; set; }
        public virtual DbSet<AS_TpGuiaSetor> AS_TpGuiaSetor { get; set; }
        public virtual DbSet<AS_TpProced> AS_TpProced { get; set; }
        public virtual DbSet<AS_TurnoAtend> AS_TurnoAtend { get; set; }
        public virtual DbSet<ASSMED_Abas> ASSMED_Abas { get; set; }
        public virtual DbSet<ASSMED_AcaoSocial> ASSMED_AcaoSocial { get; set; }
        public virtual DbSet<ASSMED_Acesso> ASSMED_Acesso { get; set; }
        public virtual DbSet<ASSMED_AtendAcaoSocial> ASSMED_AtendAcaoSocial { get; set; }
        public virtual DbSet<ASSMED_AtendCidadao> ASSMED_AtendCidadao { get; set; }
        public virtual DbSet<ASSMED_AtendEncaminha> ASSMED_AtendEncaminha { get; set; }
        public virtual DbSet<ASSMED_Atendimento> ASSMED_Atendimento { get; set; }
        public virtual DbSet<ASSMED_AvaliacaoFisica> ASSMED_AvaliacaoFisica { get; set; }
        public virtual DbSet<ASSMED_Cadastro> ASSMED_Cadastro { get; set; }
        public virtual DbSet<ASSMED_CadastroAcaoSocial> ASSMED_CadastroAcaoSocial { get; set; }
        public virtual DbSet<ASSMED_CadastroCertidoes> ASSMED_CadastroCertidoes { get; set; }
        public virtual DbSet<ASSMED_CadastroConv> ASSMED_CadastroConv { get; set; }
        public virtual DbSet<ASSMED_CadastroDocPessoal> ASSMED_CadastroDocPessoal { get; set; }
        public virtual DbSet<ASSMED_CadastroFoto> ASSMED_CadastroFoto { get; set; }
        public virtual DbSet<ASSMED_CadastroPF> ASSMED_CadastroPF { get; set; }
        public virtual DbSet<ASSMED_CadastroQuest> ASSMED_CadastroQuest { get; set; }
        public virtual DbSet<ASSMED_CadastroQuestResp> ASSMED_CadastroQuestResp { get; set; }
        public virtual DbSet<ASSMED_CadastroQuestRespL> ASSMED_CadastroQuestRespL { get; set; }
        public virtual DbSet<ASSMED_CadastroQuestRespM> ASSMED_CadastroQuestRespM { get; set; }
        public virtual DbSet<ASSMED_CadastroQuestRespN> ASSMED_CadastroQuestRespN { get; set; }
        public virtual DbSet<ASSMED_CadastroQuestRespT> ASSMED_CadastroQuestRespT { get; set; }
        public virtual DbSet<ASSMED_CadastroQuestRespV> ASSMED_CadastroQuestRespV { get; set; }
        public virtual DbSet<ASSMED_CadastroSetor> ASSMED_CadastroSetor { get; set; }
        public virtual DbSet<ASSMED_CadastroTitular> ASSMED_CadastroTitular { get; set; }
        public virtual DbSet<ASSMED_CadastroVacina> ASSMED_CadastroVacina { get; set; }
        public virtual DbSet<ASSMED_CadEmails> ASSMED_CadEmails { get; set; }
        public virtual DbSet<ASSMED_ConselhoClasse> ASSMED_ConselhoClasse { get; set; }
        public virtual DbSet<ASSMED_Contratos> ASSMED_Contratos { get; set; }
        public virtual DbSet<ASSMED_ContratoUsuario> ASSMED_ContratoUsuario { get; set; }
        public virtual DbSet<ASSMED_Cursos> ASSMED_Cursos { get; set; }
        public virtual DbSet<ASSMED_CursosTurmas> ASSMED_CursosTurmas { get; set; }
        public virtual DbSet<ASSMED_CursosTurmasAlunos> ASSMED_CursosTurmasAlunos { get; set; }
        public virtual DbSet<ASSMED_CursosTurmasHoras> ASSMED_CursosTurmasHoras { get; set; }
        public virtual DbSet<ASSMED_Direitos> ASSMED_Direitos { get; set; }
        public virtual DbSet<ASSMED_DOENCAS> ASSMED_DOENCAS { get; set; }
        public virtual DbSet<ASSMED_Endereco> ASSMED_Endereco { get; set; }
        public virtual DbSet<ASSMED_MatExames> ASSMED_MatExames { get; set; }
        public virtual DbSet<ASSMED_MatriculaCassems> ASSMED_MatriculaCassems { get; set; }
        public virtual DbSet<ASSMED_Orgaos> ASSMED_Orgaos { get; set; }
        public virtual DbSet<ASSMED_Parentesco> ASSMED_Parentesco { get; set; }
        public virtual DbSet<ASSMED_PerguntaPadraoMulProx> ASSMED_PerguntaPadraoMulProx { get; set; }
        public virtual DbSet<ASSMED_PerguntaPadraoMult> ASSMED_PerguntaPadraoMult { get; set; }
        public virtual DbSet<ASSMED_PerguntasPadrao> ASSMED_PerguntasPadrao { get; set; }
        public virtual DbSet<ASSMED_PesFisica> ASSMED_PesFisica { get; set; }
        public virtual DbSet<ASSMED_PesJuridica> ASSMED_PesJuridica { get; set; }
        public virtual DbSet<ASSMED_Profissionais> ASSMED_Profissionais { get; set; }
        public virtual DbSet<ASSMED_Programa> ASSMED_Programa { get; set; }
        public virtual DbSet<ASSMED_ProgramaCampos> ASSMED_ProgramaCampos { get; set; }
        public virtual DbSet<ASSMED_Questionarios> ASSMED_Questionarios { get; set; }
        public virtual DbSet<ASSMED_QuestionariosPerguntas> ASSMED_QuestionariosPerguntas { get; set; }
        public virtual DbSet<ASSMED_RecPagPadrao> ASSMED_RecPagPadrao { get; set; }
        public virtual DbSet<ASSMED_SALAS> ASSMED_SALAS { get; set; }
        public virtual DbSet<ASSMED_SALASAgenda> ASSMED_SALASAgenda { get; set; }
        public virtual DbSet<ASSMED_SALASAgendaOcorrencia> ASSMED_SALASAgendaOcorrencia { get; set; }
        public virtual DbSet<ASSMED_SALASPRESENCA> ASSMED_SALASPRESENCA { get; set; }
        public virtual DbSet<ASSMED_SALASTURMA> ASSMED_SALASTURMA { get; set; }
        public virtual DbSet<ASSMED_SALASTURMASHORAS> ASSMED_SALASTURMASHORAS { get; set; }
        public virtual DbSet<ASSMED_SalasTurmaValor> ASSMED_SalasTurmaValor { get; set; }
        public virtual DbSet<ASSMED_Secao> ASSMED_Secao { get; set; }
        public virtual DbSet<ASSMED_Sistema> ASSMED_Sistema { get; set; }
        public virtual DbSet<ASSMED_SistemaSecao> ASSMED_SistemaSecao { get; set; }
        public virtual DbSet<ASSMED_SistemaUsuario> ASSMED_SistemaUsuario { get; set; }
        public virtual DbSet<ASSMED_SituacaoMatricula> ASSMED_SituacaoMatricula { get; set; }
        public virtual DbSet<ASSMED_Suporte> ASSMED_Suporte { get; set; }
        public virtual DbSet<ASSMED_SuporteAnda> ASSMED_SuporteAnda { get; set; }
        public virtual DbSet<ASSMED_TabelaICQ> ASSMED_TabelaICQ { get; set; }
        public virtual DbSet<ASSMED_TipoCertidoes> ASSMED_TipoCertidoes { get; set; }
        public virtual DbSet<ASSMED_TipoDocPessoal> ASSMED_TipoDocPessoal { get; set; }
        public virtual DbSet<ASSMED_TurmaMatricula> ASSMED_TurmaMatricula { get; set; }
        public virtual DbSet<ASSMED_TurmaMatriculaSit> ASSMED_TurmaMatriculaSit { get; set; }
        public virtual DbSet<ASSMED_Usuario> ASSMED_Usuario { get; set; }
        public virtual DbSet<ASSMED_UsuarioSetor> ASSMED_UsuarioSetor { get; set; }
        public virtual DbSet<ASSMED_VacinaConfRel> ASSMED_VacinaConfRel { get; set; }
        public virtual DbSet<ASSMED_Vacinas> ASSMED_Vacinas { get; set; }
        public virtual DbSet<ASSMED_VacinasCombate> ASSMED_VacinasCombate { get; set; }
        public virtual DbSet<ASSMED_VacinaSolicita> ASSMED_VacinaSolicita { get; set; }
        public virtual DbSet<ASSMED_VacinasValor> ASSMED_VacinasValor { get; set; }
        public virtual DbSet<AssRel> AssRel { get; set; }
        public virtual DbSet<Atendimento_Individual> Atendimento_Individual { get; set; }
        public virtual DbSet<Atendimento_Individual_Exames> Atendimento_Individual_Exames { get; set; }
        public virtual DbSet<Atendimento_Individual_Profissional_Saude> Atendimento_Individual_Profissional_Saude { get; set; }
        public virtual DbSet<Atendimento_Individual_Usuario> Atendimento_Individual_Usuario { get; set; }
        public virtual DbSet<BB_Acervo> BB_Acervo { get; set; }
        public virtual DbSet<BB_AcervoAssunto> BB_AcervoAssunto { get; set; }
        public virtual DbSet<BB_AcervoAutor> BB_AcervoAutor { get; set; }
        public virtual DbSet<BB_AcervoSit> BB_AcervoSit { get; set; }
        public virtual DbSet<BB_Assunto> BB_Assunto { get; set; }
        public virtual DbSet<BB_Autor> BB_Autor { get; set; }
        public virtual DbSet<BB_Editora> BB_Editora { get; set; }
        public virtual DbSet<BB_Emprestimo> BB_Emprestimo { get; set; }
        public virtual DbSet<BB_ListaEspera> BB_ListaEspera { get; set; }
        public virtual DbSet<BB_Situacao> BB_Situacao { get; set; }
        public virtual DbSet<BB_TiposAcervo> BB_TiposAcervo { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Composicao_Familiar> Composicao_Familiar { get; set; }
        public virtual DbSet<Contratos> Contratos { get; set; }
        public virtual DbSet<Deficiencias> Deficiencias { get; set; }
        public virtual DbSet<Domicilio> Domicilio { get; set; }
        public virtual DbSet<Domicilio_Alimentacao> Domicilio_Alimentacao { get; set; }
        public virtual DbSet<Domicilio_Animal> Domicilio_Animal { get; set; }
        public virtual DbSet<Domicilio_DCardiaco> Domicilio_DCardiaco { get; set; }
        public virtual DbSet<Domicilio_Deficiencia> Domicilio_Deficiencia { get; set; }
        public virtual DbSet<Domicilio_DRenal> Domicilio_DRenal { get; set; }
        public virtual DbSet<Domicilio_DRespiratorio> Domicilio_DRespiratorio { get; set; }
        public virtual DbSet<Domicilio_Familia> Domicilio_Familia { get; set; }
        public virtual DbSet<Domicilio_Higiene> Domicilio_Higiene { get; set; }
        public virtual DbSet<Domicilio_Individual> Domicilio_Individual { get; set; }
        public virtual DbSet<Etnia> Etnia { get; set; }
        public virtual DbSet<Grau_Parentesco> Grau_Parentesco { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Grupo_Menu> Grupo_Menu { get; set; }
        public virtual DbSet<grupo_Sistemas> grupo_Sistemas { get; set; }
        public virtual DbSet<Grupo_Usuario> Grupo_Usuario { get; set; }
        public virtual DbSet<IMO_Caracteristicas> IMO_Caracteristicas { get; set; }
        public virtual DbSet<IMO_Corretores> IMO_Corretores { get; set; }
        public virtual DbSet<IMO_Finalidade> IMO_Finalidade { get; set; }
        public virtual DbSet<IMO_Imobiliaria> IMO_Imobiliaria { get; set; }
        public virtual DbSet<IMO_Imovel> IMO_Imovel { get; set; }
        public virtual DbSet<IMO_ImovelCaracteristicas> IMO_ImovelCaracteristicas { get; set; }
        public virtual DbSet<IMO_ImovelCorretores> IMO_ImovelCorretores { get; set; }
        public virtual DbSet<IMO_ImovelFinalidade> IMO_ImovelFinalidade { get; set; }
        public virtual DbSet<IMO_ImovelFotos> IMO_ImovelFotos { get; set; }
        public virtual DbSet<IMO_ImovelImobiliaria> IMO_ImovelImobiliaria { get; set; }
        public virtual DbSet<IMO_ImovelLocalizacao> IMO_ImovelLocalizacao { get; set; }
        public virtual DbSet<IMO_ImovelProprietario> IMO_ImovelProprietario { get; set; }
        public virtual DbSet<IMO_Parceiros> IMO_Parceiros { get; set; }
        public virtual DbSet<IMO_TipoImovel> IMO_TipoImovel { get; set; }
        public virtual DbSet<ImuArmazenamentos> ImuArmazenamentos { get; set; }
        public virtual DbSet<ImuAtendimentos> ImuAtendimentos { get; set; }
        public virtual DbSet<ImuAtendimentos_Doses> ImuAtendimentos_Doses { get; set; }
        public virtual DbSet<ImuCalendarios> ImuCalendarios { get; set; }
        public virtual DbSet<ImuCalendarios_Vacinas> ImuCalendarios_Vacinas { get; set; }
        public virtual DbSet<ImuCampanhas> ImuCampanhas { get; set; }
        public virtual DbSet<ImuCampanhas_Vacinas> ImuCampanhas_Vacinas { get; set; }
        public virtual DbSet<ImuVacinas> ImuVacinas { get; set; }
        public virtual DbSet<ImuVacinas_Doses> ImuVacinas_Doses { get; set; }
        public virtual DbSet<ImuVacinas_Procedimentos> ImuVacinas_Procedimentos { get; set; }
        public virtual DbSet<ImuVacinas_Produtos> ImuVacinas_Produtos { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<ProAtendimentos> ProAtendimentos { get; set; }
        public virtual DbSet<ProAtendimentos_A_TpServico> ProAtendimentos_A_TpServico { get; set; }
        public virtual DbSet<ProAtendimentos_At_A_CIAP2> ProAtendimentos_At_A_CIAP2 { get; set; }
        public virtual DbSet<ProAtendimentos_At_O_EXAMES> ProAtendimentos_At_O_EXAMES { get; set; }
        public virtual DbSet<ProAtendimentos_At_Odonto> ProAtendimentos_At_Odonto { get; set; }
        public virtual DbSet<ProAtendimentos_At_P_CIAP2> ProAtendimentos_At_P_CIAP2 { get; set; }
        public virtual DbSet<ProAtendimentos_At_S_CIAP2> ProAtendimentos_At_S_CIAP2 { get; set; }
        public virtual DbSet<ProAtendimentos_At_SIGTAP> ProAtendimentos_At_SIGTAP { get; set; }
        public virtual DbSet<ProAtendimentos_At_TpServico> ProAtendimentos_At_TpServico { get; set; }
        public virtual DbSet<ProAtendimentos_EI_SIGTAP> ProAtendimentos_EI_SIGTAP { get; set; }
        public virtual DbSet<ProAtendimentos_EI_TpServico> ProAtendimentos_EI_TpServico { get; set; }
        public virtual DbSet<ProAtendimentos_Status> ProAtendimentos_Status { get; set; }
        public virtual DbSet<ProAtendimentos_TpServicos> ProAtendimentos_TpServicos { get; set; }
        public virtual DbSet<PT_FeriadosFixos> PT_FeriadosFixos { get; set; }
        public virtual DbSet<PT_FeriadosMoveis> PT_FeriadosMoveis { get; set; }
        public virtual DbSet<RegimeJuridico> RegimeJuridico { get; set; }
        public virtual DbSet<RelUsuario> RelUsuario { get; set; }
        public virtual DbSet<Seletor> Seletor { get; set; }
        public virtual DbSet<Setores> Setores { get; set; }
        public virtual DbSet<setores_TipoExames> setores_TipoExames { get; set; }
        public virtual DbSet<SetoresAlas> SetoresAlas { get; set; }
        public virtual DbSet<SetoresClassificacao> SetoresClassificacao { get; set; }
        public virtual DbSet<SetoresINEs> SetoresINEs { get; set; }
        public virtual DbSet<SetorUsuario> SetorUsuario { get; set; }
        public virtual DbSet<SIGSM_Acao_Estruturante_Atividade> SIGSM_Acao_Estruturante_Atividade { get; set; }
        public virtual DbSet<SIGSM_Acao_Estruturante_Temas_Reuniao> SIGSM_Acao_Estruturante_Temas_Reuniao { get; set; }
        public virtual DbSet<SIGSM_Acao_Saude_Atividade> SIGSM_Acao_Saude_Atividade { get; set; }
        public virtual DbSet<SIGSM_Acao_Saude_Publico_Alvo> SIGSM_Acao_Saude_Publico_Alvo { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Domiciliar> SIGSM_Atendimento_Domiciliar { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Domiciliar_Paciente> SIGSM_Atendimento_Domiciliar_Paciente { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Domiciliar_Procedimentos> SIGSM_Atendimento_Domiciliar_Procedimentos { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Domiciliar_Profissional> SIGSM_Atendimento_Domiciliar_Profissional { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Individual_Usuario_Condutas> SIGSM_Atendimento_Individual_Usuario_Condutas { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Odontologico> SIGSM_Atendimento_Odontologico { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Odontologico_Paciente> SIGSM_Atendimento_Odontologico_Paciente { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Odontologico_Procedimentos> SIGSM_Atendimento_Odontologico_Procedimentos { get; set; }
        public virtual DbSet<SIGSM_Atendimento_Odontologico_Profissional> SIGSM_Atendimento_Odontologico_Profissional { get; set; }
        public virtual DbSet<SIGSM_Atividade_Coletiva> SIGSM_Atividade_Coletiva { get; set; }
        public virtual DbSet<SIGSM_Atividade_Coletiva_Praticas_Temas_Para_Saude> SIGSM_Atividade_Coletiva_Praticas_Temas_Para_Saude { get; set; }
        public virtual DbSet<SIGSM_Atividade_Coletiva_Profissional_Saude> SIGSM_Atividade_Coletiva_Profissional_Saude { get; set; }
        public virtual DbSet<SIGSM_Atividade_Coletiva_Publico_Alvo> SIGSM_Atividade_Coletiva_Publico_Alvo { get; set; }
        public virtual DbSet<SIGSM_Atividade_Coletiva_Temas_Reuniao> SIGSM_Atividade_Coletiva_Temas_Reuniao { get; set; }
        public virtual DbSet<SIGSM_Atividade_Coletiva_Usuario> SIGSM_Atividade_Coletiva_Usuario { get; set; }
        public virtual DbSet<SIGSM_Avaliacao_Elegibilidade_Admissao> SIGSM_Avaliacao_Elegibilidade_Admissao { get; set; }
        public virtual DbSet<SIGSM_Avaliacao_Elegibilidade_Admissao_Paciente> SIGSM_Avaliacao_Elegibilidade_Admissao_Paciente { get; set; }
        public virtual DbSet<SIGSM_Avaliacao_Elegibilidade_Admissao_Profissional> SIGSM_Avaliacao_Elegibilidade_Admissao_Profissional { get; set; }
        public virtual DbSet<SIGSM_CamposTela> SIGSM_CamposTela { get; set; }
        public virtual DbSet<SIGSM_Crianca_Mais_2_Anos_Adolescente_Adulto_Gestante_Idoso> SIGSM_Crianca_Mais_2_Anos_Adolescente_Adulto_Gestante_Idoso { get; set; }
        public virtual DbSet<SIGSM_Crianca_Menor_Seis_Meses> SIGSM_Crianca_Menor_Seis_Meses { get; set; }
        public virtual DbSet<SIGSM_Crianca_Seis_a_23_Meses> SIGSM_Crianca_Seis_a_23_Meses { get; set; }
        public virtual DbSet<SIGSM_Domiciliar_Condicoes> SIGSM_Domiciliar_Condicoes { get; set; }
        public virtual DbSet<SIGSM_Domiciliar_Conduta_Motivo> SIGSM_Domiciliar_Conduta_Motivo { get; set; }
        public virtual DbSet<SIGSM_Domiciliar_Procedimentos> SIGSM_Domiciliar_Procedimentos { get; set; }
        public virtual DbSet<SIGSM_GrupoCampos> SIGSM_GrupoCampos { get; set; }
        public virtual DbSet<SIGSM_Marcadores_Consumo_Alimentar> SIGSM_Marcadores_Consumo_Alimentar { get; set; }
        public virtual DbSet<SIGSM_MotivoVisita> SIGSM_MotivoVisita { get; set; }
        public virtual DbSet<SIGSM_Odontologico_Conduta> SIGSM_Odontologico_Conduta { get; set; }
        public virtual DbSet<SIGSM_Odontologico_Procedimentos> SIGSM_Odontologico_Procedimentos { get; set; }
        public virtual DbSet<SIGSM_Odontologico_Vigilancia> SIGSM_Odontologico_Vigilancia { get; set; }
        public virtual DbSet<SIGSM_Praticas_Temas_Para_Saude> SIGSM_Praticas_Temas_Para_Saude { get; set; }
        public virtual DbSet<SIGSM_Procedimento> SIGSM_Procedimento { get; set; }
        public virtual DbSet<SIGSM_Procedimento_Sigtap> SIGSM_Procedimento_Sigtap { get; set; }
        public virtual DbSet<SIGSM_Procedimento_Usuario> SIGSM_Procedimento_Usuario { get; set; }
        public virtual DbSet<SIGSM_Status> SIGSM_Status { get; set; }
        public virtual DbSet<SIGSM_Tela> SIGSM_Tela { get; set; }
        public virtual DbSet<SIGSM_Tipo_Procedimento> SIGSM_Tipo_Procedimento { get; set; }
        public virtual DbSet<SIGSM_Visita_Domiciliar> SIGSM_Visita_Domiciliar { get; set; }
        public virtual DbSet<SIGSM_Visita_Domiciliar_Paciente> SIGSM_Visita_Domiciliar_Paciente { get; set; }
        public virtual DbSet<SituacaoFamiliar> SituacaoFamiliar { get; set; }
        public virtual DbSet<SituacaoFuncional> SituacaoFuncional { get; set; }
        public virtual DbSet<SPZ_Pedido> SPZ_Pedido { get; set; }
        public virtual DbSet<SPZ_PedidoItens> SPZ_PedidoItens { get; set; }
        public virtual DbSet<SPZ_PedidoItensAcessorio> SPZ_PedidoItensAcessorio { get; set; }
        public virtual DbSet<SPZ_PedidoItensIng> SPZ_PedidoItensIng { get; set; }
        public virtual DbSet<SPZ_PedidoStatus> SPZ_PedidoStatus { get; set; }
        public virtual DbSet<Terceiros_tipoExames> Terceiros_tipoExames { get; set; }
        public virtual DbSet<Tipo_Atendimento> Tipo_Atendimento { get; set; }
        public virtual DbSet<TP_Abastecimento_Agua> TP_Abastecimento_Agua { get; set; }
        public virtual DbSet<TP_Acesso_Domicilio> TP_Acesso_Domicilio { get; set; }
        public virtual DbSet<TP_Animais> TP_Animais { get; set; }
        public virtual DbSet<TP_Cond_Posse_Uso_Terra> TP_Cond_Posse_Uso_Terra { get; set; }
        public virtual DbSet<TP_Condicao_Avaliada> TP_Condicao_Avaliada { get; set; }
        public virtual DbSet<TP_Consideracao_Peso> TP_Consideracao_Peso { get; set; }
        public virtual DbSet<TP_Construcao_Domicilio> TP_Construcao_Domicilio { get; set; }
        public virtual DbSet<TP_Crianca> TP_Crianca { get; set; }
        public virtual DbSet<TP_Curso> TP_Curso { get; set; }
        public virtual DbSet<TP_Deficiencia> TP_Deficiencia { get; set; }
        public virtual DbSet<TP_Destino_Lixo> TP_Destino_Lixo { get; set; }
        public virtual DbSet<TP_Doenca_Cardiaca> TP_Doenca_Cardiaca { get; set; }
        public virtual DbSet<TP_Doenca_Renal> TP_Doenca_Renal { get; set; }
        public virtual DbSet<TP_Doenca_Respiratoria> TP_Doenca_Respiratoria { get; set; }
        public virtual DbSet<TP_Domicilio> TP_Domicilio { get; set; }
        public virtual DbSet<TP_Escoamento_Esgoto> TP_Escoamento_Esgoto { get; set; }
        public virtual DbSet<TP_Exames> TP_Exames { get; set; }
        public virtual DbSet<TP_Higiene_Pessoal> TP_Higiene_Pessoal { get; set; }
        public virtual DbSet<TP_Identidade_Genero_Cidadao> TP_Identidade_Genero_Cidadao { get; set; }
        public virtual DbSet<TP_Imovel> TP_Imovel { get; set; }
        public virtual DbSet<TP_Localizacao> TP_Localizacao { get; set; }
        public virtual DbSet<TP_Motivo_Saida> TP_Motivo_Saida { get; set; }
        public virtual DbSet<TP_Nacionalidade> TP_Nacionalidade { get; set; }
        public virtual DbSet<TP_Orientacao_Sexual> TP_Orientacao_Sexual { get; set; }
        public virtual DbSet<TP_Origem_Alimentacao> TP_Origem_Alimentacao { get; set; }
        public virtual DbSet<TP_Quantas_Vezes_Alimentacao> TP_Quantas_Vezes_Alimentacao { get; set; }
        public virtual DbSet<TP_Raca_Cor> TP_Raca_Cor { get; set; }
        public virtual DbSet<TP_Relacao_Parentesco> TP_Relacao_Parentesco { get; set; }
        public virtual DbSet<TP_Renda_Familiar> TP_Renda_Familiar { get; set; }
        public virtual DbSet<TP_Saida_Cadastro> TP_Saida_Cadastro { get; set; }
        public virtual DbSet<TP_Sexo> TP_Sexo { get; set; }
        public virtual DbSet<TP_Sexo_Genero> TP_Sexo_Genero { get; set; }
        public virtual DbSet<TP_Sit_Mercado> TP_Sit_Mercado { get; set; }
        public virtual DbSet<TP_Sit_Rua> TP_Sit_Rua { get; set; }
        public virtual DbSet<TP_Situacao_Moradia> TP_Situacao_Moradia { get; set; }
        public virtual DbSet<TP_Situacao_Moradia_Rural> TP_Situacao_Moradia_Rural { get; set; }
        public virtual DbSet<TP_Tratamento_Agua> TP_Tratamento_Agua { get; set; }
        public virtual DbSet<TU_Classificacao> TU_Classificacao { get; set; }
        public virtual DbSet<TU_Equipe> TU_Equipe { get; set; }
        public virtual DbSet<TU_Regra> TU_Regra { get; set; }
        public virtual DbSet<TU_Servico> TU_Servico { get; set; }
        public virtual DbSet<TU_TabelaProcClass> TU_TabelaProcClass { get; set; }
        public virtual DbSet<TU_TabelaProcRegra> TU_TabelaProcRegra { get; set; }
        public virtual DbSet<UF> UF { get; set; }
        public virtual DbSet<AE_MovimentaItemOLD> AE_MovimentaItemOLD { get; set; }
        public virtual DbSet<ARQ020> ARQ020 { get; set; }
        public virtual DbSet<AS_ExcluidosAgenda> AS_ExcluidosAgenda { get; set; }
        public virtual DbSet<ASSMED_CadastroExamesBloqueados> ASSMED_CadastroExamesBloqueados { get; set; }
        public virtual DbSet<ASSMED_CadTelefones> ASSMED_CadTelefones { get; set; }
        public virtual DbSet<AssRelCampos> AssRelCampos { get; set; }
        public virtual DbSet<CEP_BAI> CEP_BAI { get; set; }
        public virtual DbSet<CEP_LOC> CEP_LOC { get; set; }
        public virtual DbSet<CEP_LOG> CEP_LOG { get; set; }
        public virtual DbSet<chatAuditoria> chatAuditoria { get; set; }
        public virtual DbSet<ConfiguracoesGerais> ConfiguracoesGerais { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Erros> Erros { get; set; }
        public virtual DbSet<Nacionalidade> Nacionalidade { get; set; }
        public virtual DbSet<OrgaoEmissor> OrgaoEmissor { get; set; }
        public virtual DbSet<PMD018> PMD018 { get; set; }
        public virtual DbSet<RacaCor> RacaCor { get; set; }
        public virtual DbSet<Setores_Cotas> Setores_Cotas { get; set; }
        public virtual DbSet<SIGSM_Ciap> SIGSM_Ciap { get; set; }
        public virtual DbSet<SigTap_Atendimento_Odontologico> SigTap_Atendimento_Odontologico { get; set; }
        public virtual DbSet<TB_CidadaoSocial> TB_CidadaoSocial { get; set; }
        public virtual DbSet<TB_MS_TIPO_LOGRADOURO> TB_MS_TIPO_LOGRADOURO { get; set; }
        public virtual DbSet<Tb_produto> Tb_produto { get; set; }
        public virtual DbSet<tb_TelefonesCidadao> tb_TelefonesCidadao { get; set; }
        public virtual DbSet<tb_unidadeMedida> tb_unidadeMedida { get; set; }
        public virtual DbSet<TipoCertidao> TipoCertidao { get; set; }
        public virtual DbSet<TipoLogradouro> TipoLogradouro { get; set; }
        public virtual DbSet<TP_Conduta> TP_Conduta { get; set; }
        public virtual DbSet<TP_Nasf> TP_Nasf { get; set; }
        public virtual DbSet<ProAtendimentos_Listagem> ProAtendimentos_Listagem { get; set; }
        public virtual DbSet<VW_ATENDIMENTO_DOMICILIAR> VW_ATENDIMENTO_DOMICILIAR { get; set; }
        public virtual DbSet<VW_ATENDIMENTO_INDIVIDUAL> VW_ATENDIMENTO_INDIVIDUAL { get; set; }
        public virtual DbSet<VW_ATENDIMENTO_ODONTOLOGICO> VW_ATENDIMENTO_ODONTOLOGICO { get; set; }
        public virtual DbSet<VW_ATIVIDADE_COLETIVA> VW_ATIVIDADE_COLETIVA { get; set; }
        public virtual DbSet<VW_AVALIACAO_ELEGIBILIDADE_ADMISSAO> VW_AVALIACAO_ELEGIBILIDADE_ADMISSAO { get; set; }
        public virtual DbSet<VW_COMP_FAMILIAR> VW_COMP_FAMILIAR { get; set; }
        public virtual DbSet<VW_DOMICILIO> VW_DOMICILIO { get; set; }
        public virtual DbSet<VW_GRUPO> VW_GRUPO { get; set; }
        public virtual DbSet<VW_INDIVIDUAIS> VW_INDIVIDUAIS { get; set; }
        public virtual DbSet<VW_MARCADORES_CONSUMO_ALIMENTAR> VW_MARCADORES_CONSUMO_ALIMENTAR { get; set; }
        public virtual DbSet<VW_PROCEDIMENTO> VW_PROCEDIMENTO { get; set; }
        public virtual DbSet<Vw_Relatorios_AtendimentoCredenciado> Vw_Relatorios_AtendimentoCredenciado { get; set; }
        public virtual DbSet<Vw_Relatorios_BPA> Vw_Relatorios_BPA { get; set; }
        public virtual DbSet<VW_USUARIO> VW_USUARIO { get; set; }
        public virtual DbSet<VW_VISITA_DOMICILIAR> VW_VISITA_DOMICILIAR { get; set; }
        public virtual DbSet<TipoOrigem> TipoOrigem { get; set; }
        public virtual DbSet<TipoOrigemVisita> TipoOrigemVisita { get; set; }
    
        public virtual int PR_ProcessarFichasAPI(Nullable<System.Guid> token)
        {
            var tokenParameter = token.HasValue ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ProcessarFichasAPI", tokenParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> PR_INT_EnviarCabecalho(string profissionalCNS, string cboCodigo_2002, string cnes, Nullable<long> dataAtendimento, string codigoIbgeMunicipio, string ine, Nullable<int> tipoOrigem)
        {
            var profissionalCNSParameter = profissionalCNS != null ?
                new ObjectParameter("profissionalCNS", profissionalCNS) :
                new ObjectParameter("profissionalCNS", typeof(string));
    
            var cboCodigo_2002Parameter = cboCodigo_2002 != null ?
                new ObjectParameter("cboCodigo_2002", cboCodigo_2002) :
                new ObjectParameter("cboCodigo_2002", typeof(string));
    
            var cnesParameter = cnes != null ?
                new ObjectParameter("cnes", cnes) :
                new ObjectParameter("cnes", typeof(string));
    
            var dataAtendimentoParameter = dataAtendimento.HasValue ?
                new ObjectParameter("dataAtendimento", dataAtendimento) :
                new ObjectParameter("dataAtendimento", typeof(long));
    
            var codigoIbgeMunicipioParameter = codigoIbgeMunicipio != null ?
                new ObjectParameter("codigoIbgeMunicipio", codigoIbgeMunicipio) :
                new ObjectParameter("codigoIbgeMunicipio", typeof(string));
    
            var ineParameter = ine != null ?
                new ObjectParameter("ine", ine) :
                new ObjectParameter("ine", typeof(string));
    
            var tipoOrigemParameter = tipoOrigem.HasValue ?
                new ObjectParameter("tipoOrigem", tipoOrigem) :
                new ObjectParameter("tipoOrigem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("PR_INT_EnviarCabecalho", profissionalCNSParameter, cboCodigo_2002Parameter, cnesParameter, dataAtendimentoParameter, codigoIbgeMunicipioParameter, ineParameter, tipoOrigemParameter);
        }
    
        public virtual int PR_INT_EnviarFicha(Nullable<System.Guid> token, Nullable<int> turno, Nullable<int> desfecho, Nullable<int> tipoDeImovel, string cnsCidadao, Nullable<long> dataNascimento, Nullable<int> sexo, string microarea, Nullable<bool> stForaArea, Nullable<int> tipoOrigem, string numProntuario, Nullable<decimal> pesoAcompanhamentoNutricional, Nullable<decimal> alturaAcompanhamentoNutricional, Nullable<bool> statusVisitaCompartilhadaOutroProfissional)
        {
            var tokenParameter = token.HasValue ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(System.Guid));
    
            var turnoParameter = turno.HasValue ?
                new ObjectParameter("turno", turno) :
                new ObjectParameter("turno", typeof(int));
    
            var desfechoParameter = desfecho.HasValue ?
                new ObjectParameter("desfecho", desfecho) :
                new ObjectParameter("desfecho", typeof(int));
    
            var tipoDeImovelParameter = tipoDeImovel.HasValue ?
                new ObjectParameter("tipoDeImovel", tipoDeImovel) :
                new ObjectParameter("tipoDeImovel", typeof(int));
    
            var cnsCidadaoParameter = cnsCidadao != null ?
                new ObjectParameter("cnsCidadao", cnsCidadao) :
                new ObjectParameter("cnsCidadao", typeof(string));
    
            var dataNascimentoParameter = dataNascimento.HasValue ?
                new ObjectParameter("dataNascimento", dataNascimento) :
                new ObjectParameter("dataNascimento", typeof(long));
    
            var sexoParameter = sexo.HasValue ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(int));
    
            var microareaParameter = microarea != null ?
                new ObjectParameter("microarea", microarea) :
                new ObjectParameter("microarea", typeof(string));
    
            var stForaAreaParameter = stForaArea.HasValue ?
                new ObjectParameter("stForaArea", stForaArea) :
                new ObjectParameter("stForaArea", typeof(bool));
    
            var tipoOrigemParameter = tipoOrigem.HasValue ?
                new ObjectParameter("tipoOrigem", tipoOrigem) :
                new ObjectParameter("tipoOrigem", typeof(int));
    
            var numProntuarioParameter = numProntuario != null ?
                new ObjectParameter("numProntuario", numProntuario) :
                new ObjectParameter("numProntuario", typeof(string));
    
            var pesoAcompanhamentoNutricionalParameter = pesoAcompanhamentoNutricional.HasValue ?
                new ObjectParameter("pesoAcompanhamentoNutricional", pesoAcompanhamentoNutricional) :
                new ObjectParameter("pesoAcompanhamentoNutricional", typeof(decimal));
    
            var alturaAcompanhamentoNutricionalParameter = alturaAcompanhamentoNutricional.HasValue ?
                new ObjectParameter("alturaAcompanhamentoNutricional", alturaAcompanhamentoNutricional) :
                new ObjectParameter("alturaAcompanhamentoNutricional", typeof(decimal));
    
            var statusVisitaCompartilhadaOutroProfissionalParameter = statusVisitaCompartilhadaOutroProfissional.HasValue ?
                new ObjectParameter("statusVisitaCompartilhadaOutroProfissional", statusVisitaCompartilhadaOutroProfissional) :
                new ObjectParameter("statusVisitaCompartilhadaOutroProfissional", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_INT_EnviarFicha", tokenParameter, turnoParameter, desfechoParameter, tipoDeImovelParameter, cnsCidadaoParameter, dataNascimentoParameter, sexoParameter, microareaParameter, stForaAreaParameter, tipoOrigemParameter, numProntuarioParameter, pesoAcompanhamentoNutricionalParameter, alturaAcompanhamentoNutricionalParameter, statusVisitaCompartilhadaOutroProfissionalParameter);
        }
    }
}
