//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio_Individual
    {
        public int id_domicilio_individual { get; set; }
        public Nullable<int> id_domicilio { get; set; }
        public Nullable<int> id_pessoa { get; set; }
        public string nome_social { get; set; }
        public string nr_sus { get; set; }
        public string nr_nis { get; set; }
        public Nullable<int> id_tp_Raca_Cor { get; set; }
        public Nullable<int> mae_desconhecida { get; set; }
        public Nullable<int> nacionalidade { get; set; }
        public string uf { get; set; }
        public string municipio { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string ocupacao { get; set; }
        public Nullable<int> id_tp_Sit_Mercado { get; set; }
        public Nullable<int> escola { get; set; }
        public Nullable<int> tp_Curso { get; set; }
        public Nullable<int> id_tp_Crianca { get; set; }
        public Nullable<int> cuidador_trad { get; set; }
        public Nullable<int> grp_comunitario { get; set; }
        public Nullable<int> pln_saude { get; set; }
        public Nullable<int> comunidade_trad { get; set; }
        public string comuni_desc { get; set; }
        public Nullable<int> genero { get; set; }
        public Nullable<int> id_tp_Sexo_Genero { get; set; }
        public Nullable<int> deficiencia { get; set; }
        public Nullable<int> id_tp_Saida_Cadastro { get; set; }
        public Nullable<int> gestante { get; set; }
        public string maternidade { get; set; }
        public Nullable<int> peso { get; set; }
        public Nullable<int> fumante { get; set; }
        public Nullable<int> alcool { get; set; }
        public Nullable<int> drogas { get; set; }
        public Nullable<int> hipertensao { get; set; }
        public Nullable<int> diabetes { get; set; }
        public Nullable<int> avc { get; set; }
        public Nullable<int> infarto { get; set; }
        public Nullable<int> cardiaco { get; set; }
        public Nullable<int> renal { get; set; }
        public Nullable<int> respiratorio { get; set; }
        public Nullable<int> hanseniase { get; set; }
        public Nullable<int> tuberculose { get; set; }
        public Nullable<int> interna_12m { get; set; }
        public string causa_inter_12m { get; set; }
        public Nullable<int> cancer { get; set; }
        public Nullable<int> acamado { get; set; }
        public Nullable<int> domiciliado { get; set; }
        public Nullable<int> prat_integrativa { get; set; }
        public Nullable<int> psiquiatra { get; set; }
        public Nullable<int> planta_medic { get; set; }
        public string planta_desc { get; set; }
        public string Outra1 { get; set; }
        public string Outra2 { get; set; }
        public string Outra3 { get; set; }
        public Nullable<int> sit_rua { get; set; }
        public Nullable<int> id_tp_sit_rua { get; set; }
        public Nullable<int> beneficio { get; set; }
        public Nullable<int> ref_familia { get; set; }
        public Nullable<int> qtd_alimenta { get; set; }
        public Nullable<int> outra_institu { get; set; }
        public string outra_inst_desc { get; set; }
        public Nullable<int> higiene { get; set; }
        public Nullable<int> vista_familiar { get; set; }
        public Nullable<int> id_Grau_Parentesco { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<int> id_user_cadastro { get; set; }
        public Nullable<int> id_unidade_cadastro { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<int> id_user_alteracao { get; set; }
        public Nullable<int> id_unidade_alteracao { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string guid_esus { get; set; }
        public string num_sus_prof { get; set; }
        public string num_cnes_uni { get; set; }
        public Nullable<System.DateTime> data_visita { get; set; }
        public string num_ine_eqp { get; set; }
        public string microarea { get; set; }
        public Nullable<bool> st_ficha_atualizada { get; set; }
        public Nullable<bool> st_enviado { get; set; }
        public Nullable<int> pais_nasc { get; set; }
        public string codibge_munic_nasc { get; set; }
        public string ocupacao_CodigoCbo2002 { get; set; }
    }
}
