//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FamiliaRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamiliaRow()
        {
            this.CadastroDomiciliar = new HashSet<CadastroDomiciliar>();
        }
    
        [Key]
        public System.Guid id { get; set; }
        public Nullable<int> dataNascimentoResponsavel { get; set; }
        public string numeroCnsResponsavel { get; set; }
        public Nullable<int> numeroMembrosFamilia { get; set; }
        public string numeroProntuario { get; set; }
        public Nullable<int> rendaFamiliar { get; set; }
        public Nullable<int> resideDesde { get; set; }
        public bool stMudanca { get; set; }
    
        public virtual TP_Renda_Familiar TP_Renda_Familiar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroDomiciliar> CadastroDomiciliar { get; set; }
    }
}
