
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FichaVisitaDomiciliarMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FichaVisitaDomiciliarMaster()
    {

        this.FichaVisitaDomiciliarChild = new HashSet<FichaVisitaDomiciliarChild>();

    }


    public string uuidFicha { get; set; }

    public int tpCdsOrigem { get; set; }

    public System.Guid headerTransport { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FichaVisitaDomiciliarChild> FichaVisitaDomiciliarChild { get; set; }

    public virtual UnicaLotacaoTransport UnicaLotacaoTransport { get; set; }

}

}
