//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.grupo_Sistemas = new HashSet<grupo_Sistemas>();
            this.Grupo_Menu = new HashSet<Grupo_Menu>();
            this.Grupo_Usuario = new HashSet<Grupo_Usuario>();
        }
    
        public int id_grupo { get; set; }
        public string descricao { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<int> id_user_cadastro { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<int> id_user_alteracao { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public Nullable<int> num_contrato { get; set; }
        public Nullable<int> nivelHier { get; set; }
        public Nullable<int> id_unidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_Sistemas> grupo_Sistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo_Menu> Grupo_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo_Usuario> Grupo_Usuario { get; set; }
    }
}
