//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMO_ImovelCorretores
    {
        public int NumContrato { get; set; }
        public int CodCorretor { get; set; }
        public decimal NumImovel { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
        public Nullable<int> CodUsu { get; set; }
    
        public virtual IMO_Corretores IMO_Corretores { get; set; }
        public virtual IMO_Imovel IMO_Imovel { get; set; }
    }
}
