//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMO_Corretores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMO_Corretores()
        {
            this.IMO_ImovelCorretores = new HashSet<IMO_ImovelCorretores>();
        }
    
        public int NumContrato { get; set; }
        public int CodCorretor { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public string CRECI { get; set; }
        public string UFCreci { get; set; }
    
        public virtual ASSMED_PesFisica ASSMED_PesFisica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMO_ImovelCorretores> IMO_ImovelCorretores { get; set; }
    }
}
