//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImuCampanhas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImuCampanhas()
        {
            this.ImuAtendimentos = new HashSet<ImuAtendimentos>();
            this.ImuCampanhas_Vacinas = new HashSet<ImuCampanhas_Vacinas>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string sexo { get; set; }
        public string tpIdade { get; set; }
        public Nullable<int> IdadeMin { get; set; }
        public Nullable<int> IdadeMax { get; set; }
        public Nullable<System.DateTime> dataIni { get; set; }
        public Nullable<System.DateTime> dataFin { get; set; }
        public string OBS { get; set; }
        public Nullable<int> ID_Setor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImuAtendimentos> ImuAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImuCampanhas_Vacinas> ImuCampanhas_Vacinas { get; set; }
    }
}
