
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InformacoesSocioDemograficas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public InformacoesSocioDemograficas()
    {

        this.CadastroIndividual = new HashSet<CadastroIndividual>();

        this.DeficienciasCidadao = new HashSet<DeficienciasCidadao>();

        this.ResponsavelPorCrianca = new HashSet<ResponsavelPorCrianca>();

    }


    public System.Guid id { get; set; }

    public Nullable<int> grauInstrucaoCidadao { get; set; }

    public string ocupacaoCodigoCbo2002 { get; set; }

    public Nullable<int> orientacaoSexualCidadao { get; set; }

    public string povoComunidadeTradicional { get; set; }

    public Nullable<int> relacaoParentescoCidadao { get; set; }

    public Nullable<int> situacaoMercadoTrabalhoCidadao { get; set; }

    public bool statusDesejaInformarOrientacaoSexual { get; set; }

    public bool statusFrequentaBenzedeira { get; set; }

    public bool statusFrequentaEscola { get; set; }

    public bool statusMembroPovoComunidadeTradicional { get; set; }

    public bool statusParticipaGrupoComunitario { get; set; }

    public bool statusPossuiPlanoSaudePrivado { get; set; }

    public bool statusTemAlgumaDeficiencia { get; set; }

    public Nullable<int> identidadeGeneroCidadao { get; set; }

    public bool statusDesejaInformarIdentidadeGenero { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CadastroIndividual> CadastroIndividual { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeficienciasCidadao> DeficienciasCidadao { get; set; }

    public virtual TP_Identidade_Genero_Cidadao TP_Identidade_Genero_Cidadao { get; set; }

    public virtual TP_Orientacao_Sexual TP_Orientacao_Sexual { get; set; }

    public virtual TP_Relacao_Parentesco TP_Relacao_Parentesco { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ResponsavelPorCrianca> ResponsavelPorCrianca { get; set; }

}

}
