//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Grupo_Menu = new HashSet<Grupo_Menu>();
        }
    
        public Nullable<int> id_menu_pai { get; set; }
        public Nullable<int> id_sistema { get; set; }
        public string descricao { get; set; }
        public string link { get; set; }
        public string sublink { get; set; }
        public string icone { get; set; }
        public Nullable<int> ordem { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<int> id_user_cadastro { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public int id_menu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo_Menu> Grupo_Menu { get; set; }
    }
}
