//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    
    public partial class PR_ConsultaCadastroIndividuais_Result2
    {
        public string Nome { get; set; }
        public string DtNasc { get; set; }
        public string NomeMae { get; set; }
        public string Cns { get; set; }
        public string NomeCidade { get; set; }
        public string Codigo { get; set; }
    }
}
