//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProAtendimentos_A_TpServico
    {
        public int ID { get; set; }
        public Nullable<int> ID_Atendimento { get; set; }
        public Nullable<int> ID_TpServico { get; set; }
    
        public virtual ProAtendimentos ProAtendimentos { get; set; }
        public virtual ProAtendimentos_TpServicos ProAtendimentos_TpServicos { get; set; }
    }
}
