//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProAtendimentos_At_O_EXAMES
    {
        public int ID { get; set; }
        public Nullable<int> ID_Atendimento { get; set; }
        public Nullable<int> EXAME { get; set; }
        public Nullable<System.DateTime> DATASOLICITACAO { get; set; }
        public Nullable<System.DateTime> DATAREALIZACAO { get; set; }
        public Nullable<System.DateTime> DATARESULTADO { get; set; }
        public Nullable<System.DateTime> DATAAVALIACAO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ProAtendimentos ProAtendimentos { get; set; }
    }
}
