//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProAtendimentos_Listagem
    {
        public string A_Status { get; set; }
        public Nullable<int> A_ID_Status { get; set; }
        public int A_ID { get; set; }
        public Nullable<System.DateTime> A_DataHora { get; set; }
        public Nullable<int> A_ID_Setor { get; set; }
        public string Paciente { get; set; }
        public Nullable<int> IDProfissional { get; set; }
        public string Profissional { get; set; }
        public string TpServicos { get; set; }
        public string IDsTpServicos { get; set; }
    }
}
