
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class SetoresINEs
{

    public int CodINE { get; set; }

    public Nullable<int> NumContrato { get; set; }

    public Nullable<int> CodSetor { get; set; }

    public string Numero { get; set; }

    public string Descricao { get; set; }



    public virtual Setores Setores { get; set; }

}

}
