//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setores_Cotas
    {
        public int ID { get; set; }
        public Nullable<int> NumContrato { get; set; }
        public Nullable<int> CodSetor { get; set; }
        public Nullable<int> CodProd { get; set; }
        public Nullable<int> qtdMin { get; set; }
    
        public virtual AE_Produtos AE_Produtos { get; set; }
        public virtual Setores Setores { get; set; }
    }
}
