//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGSM_CamposTela
    {
        public int id { get; set; }
        public string Nome { get; set; }
        public int id_grupo { get; set; }
        public string descricao { get; set; }
    
        public virtual SIGSM_GrupoCampos SIGSM_GrupoCampos { get; set; }
    }
}
