//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGSM_Avaliacao_Elegibilidade_Admissao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIGSM_Avaliacao_Elegibilidade_Admissao()
        {
            this.SIGSM_Avaliacao_Elegibilidade_Admissao_Paciente = new HashSet<SIGSM_Avaliacao_Elegibilidade_Admissao_Paciente>();
            this.SIGSM_Avaliacao_Elegibilidade_Admissao_Profissional = new HashSet<SIGSM_Avaliacao_Elegibilidade_Admissao_Profissional>();
        }
    
        public int id { get; set; }
        public int digitado_por { get; set; }
        public Nullable<int> conferido_por { get; set; }
        public Nullable<System.DateTime> data_avaliacao { get; set; }
        public Nullable<int> codigo_cnes_unidade { get; set; }
        public Nullable<int> codigo_equipe_ine { get; set; }
        public bool enviado { get; set; }
        public Nullable<System.DateTime> data_envio { get; set; }
        public Nullable<int> usuario_envio { get; set; }
        public int num_contrato { get; set; }
        public int id_status { get; set; }
        public string guid_esus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Avaliacao_Elegibilidade_Admissao_Paciente> SIGSM_Avaliacao_Elegibilidade_Admissao_Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Avaliacao_Elegibilidade_Admissao_Profissional> SIGSM_Avaliacao_Elegibilidade_Admissao_Profissional { get; set; }
        public virtual SIGSM_Status SIGSM_Status { get; set; }
    }
}
