//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGSM_Marcadores_Consumo_Alimentar
    {
        public long id { get; set; }
        public int digitado_por { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> conferido_por { get; set; }
        public Nullable<long> numero_folha { get; set; }
        public Nullable<decimal> id_profissional_saude { get; set; }
        public Nullable<int> NumContrato_id_profissional_saude { get; set; }
        public string cbo { get; set; }
        public Nullable<int> codigo_cnes_unidade { get; set; }
        public Nullable<int> codigo_equipe_ine { get; set; }
        public Nullable<System.DateTime> data_marcadores { get; set; }
        public string numero_cartao_sus_usuario { get; set; }
        public string nome_cidadao { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string sexo { get; set; }
        public Nullable<int> local_atendimento { get; set; }
        public Nullable<long> id_crianca_menor_seis_meses { get; set; }
        public Nullable<long> id_crianca_seis_a_23_meses { get; set; }
        public Nullable<long> id_crianca_mais_2_anos_adolescente_adulto_gestante_idoso { get; set; }
        public int id_status { get; set; }
        public Nullable<System.DateTime> data_envio { get; set; }
        public Nullable<bool> enviado { get; set; }
        public Nullable<int> usuario_envio { get; set; }
        public Nullable<decimal> id_cidadao { get; set; }
        public Nullable<int> NumContrato_cidadao { get; set; }
        public string numero_cartao_sus { get; set; }
        public string nome { get; set; }
        public string guid_esus { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual SIGSM_Crianca_Mais_2_Anos_Adolescente_Adulto_Gestante_Idoso SIGSM_Crianca_Mais_2_Anos_Adolescente_Adulto_Gestante_Idoso { get; set; }
        public virtual SIGSM_Crianca_Menor_Seis_Meses SIGSM_Crianca_Menor_Seis_Meses { get; set; }
        public virtual SIGSM_Crianca_Seis_a_23_Meses SIGSM_Crianca_Seis_a_23_Meses { get; set; }
        public virtual SIGSM_Status SIGSM_Status { get; set; }
    }
}
