//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGSM_Atividade_Coletiva_Usuario
    {
        public long id { get; set; }
        public int numero { get; set; }
        public string numero_cartao_sus { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public Nullable<bool> avaliacao_alterada { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<bool> tabagismo_cessou_habito_fumar { get; set; }
        public Nullable<bool> tabagismo_abandonou_grupo { get; set; }
        public decimal id_identificacao_usuario { get; set; }
        public int NumContrato { get; set; }
        public long id_atividade_coletiva { get; set; }
        public string nome { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual SIGSM_Atividade_Coletiva SIGSM_Atividade_Coletiva { get; set; }
    }
}
