//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGSM_Atividade_Coletiva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIGSM_Atividade_Coletiva()
        {
            this.SIGSM_Atividade_Coletiva_Praticas_Temas_Para_Saude = new HashSet<SIGSM_Atividade_Coletiva_Praticas_Temas_Para_Saude>();
            this.SIGSM_Atividade_Coletiva_Profissional_Saude = new HashSet<SIGSM_Atividade_Coletiva_Profissional_Saude>();
            this.SIGSM_Atividade_Coletiva_Publico_Alvo = new HashSet<SIGSM_Atividade_Coletiva_Publico_Alvo>();
            this.SIGSM_Atividade_Coletiva_Temas_Reuniao = new HashSet<SIGSM_Atividade_Coletiva_Temas_Reuniao>();
            this.SIGSM_Atividade_Coletiva_Usuario = new HashSet<SIGSM_Atividade_Coletiva_Usuario>();
        }
    
        public long id { get; set; }
        public int digitado_por { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> conferido_por { get; set; }
        public Nullable<long> numero_folha { get; set; }
        public Nullable<System.DateTime> data_de_atividade { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fim { get; set; }
        public Nullable<int> numero_inep_escola_creche { get; set; }
        public Nullable<int> programacao_de_numero_de_participantes { get; set; }
        public string local_de_atividades { get; set; }
        public Nullable<int> id_acao_estruturante_atividade { get; set; }
        public Nullable<int> id_acao_saude_atividade { get; set; }
        public Nullable<long> numero_cartao_sus_do_responsavel { get; set; }
        public Nullable<int> codigo_cnes_unidade { get; set; }
        public Nullable<int> numero_de_participantes { get; set; }
        public Nullable<int> numero_de_avaliacoes_alteradas { get; set; }
        public int id_status { get; set; }
        public Nullable<System.DateTime> data_envio { get; set; }
        public Nullable<bool> enviado { get; set; }
        public Nullable<int> usuario_envio { get; set; }
        public Nullable<decimal> id_responsavel { get; set; }
        public Nullable<int> NumContrato_responsavel { get; set; }
        public Nullable<int> codigo_cnes_unidade_do_responsavel { get; set; }
        public Nullable<int> codigo_equipe_ine_do_responsavel { get; set; }
        public string guid_esus { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual SIGSM_Acao_Estruturante_Atividade SIGSM_Acao_Estruturante_Atividade { get; set; }
        public virtual SIGSM_Acao_Saude_Atividade SIGSM_Acao_Saude_Atividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Atividade_Coletiva_Praticas_Temas_Para_Saude> SIGSM_Atividade_Coletiva_Praticas_Temas_Para_Saude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Atividade_Coletiva_Profissional_Saude> SIGSM_Atividade_Coletiva_Profissional_Saude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Atividade_Coletiva_Publico_Alvo> SIGSM_Atividade_Coletiva_Publico_Alvo { get; set; }
        public virtual SIGSM_Status SIGSM_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Atividade_Coletiva_Temas_Reuniao> SIGSM_Atividade_Coletiva_Temas_Reuniao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGSM_Atividade_Coletiva_Usuario> SIGSM_Atividade_Coletiva_Usuario { get; set; }
    }
}
