//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIGSM_Visita_Domiciliar_Profissional
    {
        [Key]
        public int id { get; set; }
        public int id_visita_domiciliar { get; set; }
        public decimal id_profissional { get; set; }
        public string cbo { get; set; }
        public int num_contrato { get; set; }
        public string codibge_munic_nasc { get; set; }
    
        public virtual ASSMED_Cadastro ASSMED_Cadastro { get; set; }
        public virtual SIGSM_Visita_Domiciliar SIGSM_Visita_Domiciliar { get; set; }
    }
}
