//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SigTap_Atendimento_Odontologico
    {
        public long id { get; set; }
        public string Nome { get; set; }
        public string SigTap { get; set; }
        public Nullable<int> Qtde { get; set; }
    }
}
