//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPZ_PedidoItens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPZ_PedidoItens()
        {
            this.SPZ_PedidoItensIng = new HashSet<SPZ_PedidoItensIng>();
        }
    
        public int NumContrato { get; set; }
        public int AnoPed { get; set; }
        public decimal NumPed { get; set; }
        public int itemPed { get; set; }
        public Nullable<int> CodProd1 { get; set; }
        public Nullable<int> CodProd2 { get; set; }
        public Nullable<int> QtdPed { get; set; }
        public Nullable<decimal> ValorItem { get; set; }
        public Nullable<decimal> ValorAcessorios { get; set; }
        public Nullable<decimal> ValorDesc { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public string NumIP { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
    
        public virtual SPZ_Pedido SPZ_Pedido { get; set; }
        public virtual SPZ_PedidoItensAcessorio SPZ_PedidoItensAcessorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPZ_PedidoItensIng> SPZ_PedidoItensIng { get; set; }
    }
}
