//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPZ_PedidoItensAcessorio
    {
        public int NumContrato { get; set; }
        public int AnoPed { get; set; }
        public decimal NumPed { get; set; }
        public int itemPed { get; set; }
        public Nullable<int> CodProdA { get; set; }
        public Nullable<decimal> ValorA { get; set; }
    
        public virtual SPZ_PedidoItens SPZ_PedidoItens { get; set; }
    }
}
