//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPZ_PedidoStatus
    {
        public int NumContrato { get; set; }
        public int AnoPed { get; set; }
        public decimal NumPed { get; set; }
        public string ItemSt { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DtStatus { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<System.DateTime> DtSistema { get; set; }
        public string NumIP { get; set; }
    
        public virtual SPZ_Pedido SPZ_Pedido { get; set; }
    }
}
