//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CidadaoSocial
    {
        public int NUMCID { get; set; }
        public string Código_de_Barras { get; set; }
        public string Código_da_Família { get; set; }
        public string Nome { get; set; }
        public string CNS { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string Dígito_RG { get; set; }
        public Nullable<System.DateTime> Data_de_Nascimento { get; set; }
        public string Nome_da_Mãe { get; set; }
        public string Tpo_de__Endereço { get; set; }
        public string Endereço { get; set; }
        public string Número { get; set; }
        public string Bairro { get; set; }
        public Nullable<double> Título_de_Eleitor { get; set; }
        public string Seção { get; set; }
        public string Zone_Eleitoral { get; set; }
        public string Sexo { get; set; }
        public string Profissão { get; set; }
        public string Telefone { get; set; }
        public string ds_Ddd { get; set; }
        public Nullable<int> cd_TipoTelefone { get; set; }
        public string Estado_Cívil { get; set; }
    }
}
