//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TelefonesCidadao
    {
        public int cd_Sequencia { get; set; }
        public int cd_Cidadao { get; set; }
        public string fl_Cidadao { get; set; }
        public int cd_TipoTelefone { get; set; }
        public string ds_Ddd { get; set; }
        public string ds_Telefone { get; set; }
        public string ds_Observacoes { get; set; }
        public Nullable<int> fl_Principal { get; set; }
        public string CPF { get; set; }
        public string CNS { get; set; }
        public Nullable<decimal> Codigo { get; set; }
    }
}
