//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terceiros_tipoExames
    {
        public int ID { get; set; }
        public Nullable<int> ID_Terceiros { get; set; }
        public Nullable<int> NumContrato { get; set; }
        public Nullable<int> CodTpExame { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> totalGastos { get; set; }
    
        public virtual AS_EXAMES_LOCAGEND AS_EXAMES_LOCAGEND { get; set; }
        public virtual AS_TipoExames AS_TipoExames { get; set; }
    }
}
