
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TP_EstadoCivil
{

    public string codigo { get; set; }

    public string descricao { get; set; }

}

}
