
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class TP_Situacao_Moradia_Rural
{

    public int id_tp_situacao_moradia_rural { get; set; }

    public string descricao { get; set; }

    public Nullable<int> id_user_cadastro { get; set; }

    public Nullable<int> ativo { get; set; }

    public Nullable<System.DateTime> data_cadastro { get; set; }

    public Nullable<int> id_user_alteracao { get; set; }

    public Nullable<System.DateTime> data_alteracao { get; set; }

}

}
