//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ConsultaCadastrosIndividuais
    {
        public string NomeCidadao { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string NomeMae { get; set; }
        public string CnsCidadao { get; set; }
        public string MunicipioNascimento { get; set; }
        public decimal Codigo { get; set; }
        public Nullable<System.Guid> IdFicha { get; set; }
    }
}
