//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_COMP_FAMILIAR
    {
        public int PK { get; set; }
        public int id_composicao_familiar { get; set; }
        public int codigo_pessoa { get; set; }
        public string nome { get; set; }
        public string dtnasc { get; set; }
        public Nullable<int> id_grau_parentesco { get; set; }
        public string grau_parentesco { get; set; }
        public int num_contrato { get; set; }
    }
}
