//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Profissional
    {
        public long id { get; set; }
        public string CNS { get; set; }
        public string Nome { get; set; }
        public string CBO { get; set; }
        public string Profissao { get; set; }
        public string CNES { get; set; }
        public string Unidade { get; set; }
        public string INE { get; set; }
        public string Equipe { get; set; }
        public decimal Codigo { get; set; }
        public Nullable<int> CodUsu { get; set; }
    }
}
