//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Relatorios_AtendimentoCredenciado
    {
        public decimal NumAtend { get; set; }
        public Nullable<System.DateTime> DataAtend { get; set; }
        public string HoraAtend { get; set; }
        public string NumProntuario { get; set; }
        public int NumContrato { get; set; }
        public Nullable<decimal> Codigo { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DtNasc { get; set; }
        public string CNES { get; set; }
        public int CodCred { get; set; }
        public int CodSetor { get; set; }
        public string DesSetor { get; set; }
        public string NomeMedico { get; set; }
        public string Numero { get; set; }
    }
}
