
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VW_ultimo_cadastroIndividual
{

    public decimal Codigo { get; set; }

    public System.Guid idCadastroIndividual { get; set; }

    public System.Guid headerTransport { get; set; }

    public System.Guid token { get; set; }

}

}
