
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Softpark.Models
{

using System;
    using System.Collections.Generic;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class VW_ultimo_cadastroDomiciliar
{

    public System.Guid idCadastroDomiciliar { get; set; }

    public System.Guid headerTransport { get; set; }

    public Nullable<System.Guid> token { get; set; }

    public Nullable<long> idAuto { get; set; }

    public Nullable<decimal> Codigo { get; set; }

}

}
