//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VISITAS
    {
        public long childId { get; set; }
        public string masterId { get; set; }
        public long turno { get; set; }
        public string numProntuario { get; set; }
        public string cnsCidadao { get; set; }
        public Nullable<System.DateTime> dtNascimento { get; set; }
        public Nullable<long> sexo { get; set; }
        public bool statusVisitaCompartilhadaOutroProfissional { get; set; }
        public long desfecho { get; set; }
        public string microarea { get; set; }
        public bool stForaArea { get; set; }
        public long tipoDeImovel { get; set; }
        public Nullable<decimal> pesoAcompanhamentoNutricional { get; set; }
        public Nullable<decimal> alturaAcompanhamentoNutricional { get; set; }
        public string nomeProfissional { get; set; }
        public string CBO { get; set; }
        public string Profissao { get; set; }
        public string CNES { get; set; }
        public string Unidade { get; set; }
        public string INE { get; set; }
        public string Equipe { get; set; }
        public string codigoIbgeMunicipio { get; set; }
        public Nullable<System.DateTime> dataAtendimento { get; set; }
        public Nullable<System.Guid> token { get; set; }
        public Nullable<int> CodUsu { get; set; }
        public Nullable<System.DateTime> DataModificacao { get; set; }
        public string Usuario { get; set; }
        public bool enviado { get; set; }
        public bool finalizado { get; set; }
        public string cnsProfissional { get; set; }
        public string NomePaciente { get; set; }
    }
}
