//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HigienePessoalSituacaoRua
    {
        public System.Guid id_em_situacao_de_rua { get; set; }
        public int codigo_higiene_pessoal { get; set; }
    
        public virtual EmSituacaoDeRua EmSituacaoDeRua { get; set; }
    }
}
