//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGSM_ServicoSerializador_Agenda
    {
        public System.Guid Id { get; set; }
        public System.Guid IdTransmissao { get; set; }
        public bool Executando { get; set; }
        public Nullable<System.DateTime> ExecutadoEm { get; set; }
    }
}
