// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Softpark.WS.Test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Condicoes de saáde
    /// </summary>
    public partial class CondicoesDeSaudeViewModel
    {
        /// <summary>
        /// Initializes a new instance of the CondicoesDeSaudeViewModel class.
        /// </summary>
        public CondicoesDeSaudeViewModel() { }

        /// <summary>
        /// Initializes a new instance of the CondicoesDeSaudeViewModel class.
        /// </summary>
        public CondicoesDeSaudeViewModel(string descricaoCausaInternacaoEm12Meses = default(string), string descricaoOutraCondicao1 = default(string), string descricaoOutraCondicao2 = default(string), string descricaoOutraCondicao3 = default(string), string descricaoPlantasMedicinaisUsadas = default(string), string maternidadeDeReferencia = default(string), int? situacaoPeso = default(int?), bool? statusEhDependenteAlcool = default(bool?), bool? statusEhDependenteOutrasDrogas = default(bool?), bool? statusEhFumante = default(bool?), bool? statusEhGestante = default(bool?), bool? statusEstaAcamado = default(bool?), bool? statusEstaDomiciliado = default(bool?), bool? statusTemDiabetes = default(bool?), bool? statusTemDoencaRespiratoria = default(bool?), bool? statusTemHanseniase = default(bool?), bool? statusTemHipertensaoArterial = default(bool?), bool? statusTemTeveCancer = default(bool?), bool? statusTemTeveDoencasRins = default(bool?), bool? statusTemTuberculose = default(bool?), bool? statusTeveAvcDerrame = default(bool?), bool? statusTeveDoencaCardiaca = default(bool?), bool? statusTeveInfarto = default(bool?), bool? statusTeveInternadoem12Meses = default(bool?), bool? statusUsaOutrasPraticasIntegrativasOuComplementares = default(bool?), bool? statusUsaPlantasMedicinais = default(bool?), bool? statusDiagnosticoMental = default(bool?), IList<int?> doencaCardiaca = default(IList<int?>), IList<int?> doencaRespiratoria = default(IList<int?>), IList<int?> doencaRins = default(IList<int?>))
        {
            DescricaoCausaInternacaoEm12Meses = descricaoCausaInternacaoEm12Meses;
            DescricaoOutraCondicao1 = descricaoOutraCondicao1;
            DescricaoOutraCondicao2 = descricaoOutraCondicao2;
            DescricaoOutraCondicao3 = descricaoOutraCondicao3;
            DescricaoPlantasMedicinaisUsadas = descricaoPlantasMedicinaisUsadas;
            MaternidadeDeReferencia = maternidadeDeReferencia;
            SituacaoPeso = situacaoPeso;
            StatusEhDependenteAlcool = statusEhDependenteAlcool;
            StatusEhDependenteOutrasDrogas = statusEhDependenteOutrasDrogas;
            StatusEhFumante = statusEhFumante;
            StatusEhGestante = statusEhGestante;
            StatusEstaAcamado = statusEstaAcamado;
            StatusEstaDomiciliado = statusEstaDomiciliado;
            StatusTemDiabetes = statusTemDiabetes;
            StatusTemDoencaRespiratoria = statusTemDoencaRespiratoria;
            StatusTemHanseniase = statusTemHanseniase;
            StatusTemHipertensaoArterial = statusTemHipertensaoArterial;
            StatusTemTeveCancer = statusTemTeveCancer;
            StatusTemTeveDoencasRins = statusTemTeveDoencasRins;
            StatusTemTuberculose = statusTemTuberculose;
            StatusTeveAvcDerrame = statusTeveAvcDerrame;
            StatusTeveDoencaCardiaca = statusTeveDoencaCardiaca;
            StatusTeveInfarto = statusTeveInfarto;
            StatusTeveInternadoem12Meses = statusTeveInternadoem12Meses;
            StatusUsaOutrasPraticasIntegrativasOuComplementares = statusUsaOutrasPraticasIntegrativasOuComplementares;
            StatusUsaPlantasMedicinais = statusUsaPlantasMedicinais;
            StatusDiagnosticoMental = statusDiagnosticoMental;
            DoencaCardiaca = doencaCardiaca;
            DoencaRespiratoria = doencaRespiratoria;
            DoencaRins = doencaRins;
        }

        /// <summary>
        /// Causa da internação
        /// </summary>
        [JsonProperty(PropertyName = "descricaoCausaInternacaoEm12Meses")]
        public string DescricaoCausaInternacaoEm12Meses { get; set; }

        /// <summary>
        /// Descrição 1
        /// </summary>
        [JsonProperty(PropertyName = "descricaoOutraCondicao1")]
        public string DescricaoOutraCondicao1 { get; set; }

        /// <summary>
        /// Descrição 2
        /// </summary>
        [JsonProperty(PropertyName = "descricaoOutraCondicao2")]
        public string DescricaoOutraCondicao2 { get; set; }

        /// <summary>
        /// Descrição 3
        /// </summary>
        [JsonProperty(PropertyName = "descricaoOutraCondicao3")]
        public string DescricaoOutraCondicao3 { get; set; }

        /// <summary>
        /// Plantas medicinais usadas
        /// </summary>
        [JsonProperty(PropertyName = "descricaoPlantasMedicinaisUsadas")]
        public string DescricaoPlantasMedicinaisUsadas { get; set; }

        /// <summary>
        /// Maternidade
        /// </summary>
        [JsonProperty(PropertyName = "maternidadeDeReferencia")]
        public string MaternidadeDeReferencia { get; set; }

        /// <summary>
        /// Situação do Peso
        /// </summary>
        [JsonProperty(PropertyName = "situacaoPeso")]
        public int? SituacaoPeso { get; set; }

        /// <summary>
        /// É dependente de álcool
        /// </summary>
        [JsonProperty(PropertyName = "statusEhDependenteAlcool")]
        public bool? StatusEhDependenteAlcool { get; set; }

        /// <summary>
        /// É dependente de outras drogas
        /// </summary>
        [JsonProperty(PropertyName = "statusEhDependenteOutrasDrogas")]
        public bool? StatusEhDependenteOutrasDrogas { get; set; }

        /// <summary>
        /// É fumante
        /// </summary>
        [JsonProperty(PropertyName = "statusEhFumante")]
        public bool? StatusEhFumante { get; set; }

        /// <summary>
        /// É gestante
        /// </summary>
        [JsonProperty(PropertyName = "statusEhGestante")]
        public bool? StatusEhGestante { get; set; }

        /// <summary>
        /// Está acamado
        /// </summary>
        [JsonProperty(PropertyName = "statusEstaAcamado")]
        public bool? StatusEstaAcamado { get; set; }

        /// <summary>
        /// Está domiciliado
        /// </summary>
        [JsonProperty(PropertyName = "statusEstaDomiciliado")]
        public bool? StatusEstaDomiciliado { get; set; }

        /// <summary>
        /// Tem diabetes
        /// </summary>
        [JsonProperty(PropertyName = "statusTemDiabetes")]
        public bool? StatusTemDiabetes { get; set; }

        /// <summary>
        /// Tem doença respiratória
        /// </summary>
        [JsonProperty(PropertyName = "statusTemDoencaRespiratoria")]
        public bool? StatusTemDoencaRespiratoria { get; set; }

        /// <summary>
        /// Tem hanseníase
        /// </summary>
        [JsonProperty(PropertyName = "statusTemHanseniase")]
        public bool? StatusTemHanseniase { get; set; }

        /// <summary>
        /// Tem hipertensão
        /// </summary>
        [JsonProperty(PropertyName = "statusTemHipertensaoArterial")]
        public bool? StatusTemHipertensaoArterial { get; set; }

        /// <summary>
        /// Tem/Teve câncer
        /// </summary>
        [JsonProperty(PropertyName = "statusTemTeveCancer")]
        public bool? StatusTemTeveCancer { get; set; }

        /// <summary>
        /// Tem Doença renal
        /// </summary>
        [JsonProperty(PropertyName = "statusTemTeveDoencasRins")]
        public bool? StatusTemTeveDoencasRins { get; set; }

        /// <summary>
        /// Tem Tuberculose
        /// </summary>
        [JsonProperty(PropertyName = "statusTemTuberculose")]
        public bool? StatusTemTuberculose { get; set; }

        /// <summary>
        /// Teve AVC/Derrame
        /// </summary>
        [JsonProperty(PropertyName = "statusTeveAvcDerrame")]
        public bool? StatusTeveAvcDerrame { get; set; }

        /// <summary>
        /// Teve/Tem doenca cardiaca
        /// </summary>
        [JsonProperty(PropertyName = "statusTeveDoencaCardiaca")]
        public bool? StatusTeveDoencaCardiaca { get; set; }

        /// <summary>
        /// Teve/tem infarto
        /// </summary>
        [JsonProperty(PropertyName = "statusTeveInfarto")]
        public bool? StatusTeveInfarto { get; set; }

        /// <summary>
        /// Esteve/Está internado nos últimos 12 meses
        /// </summary>
        [JsonProperty(PropertyName = "statusTeveInternadoem12Meses")]
        public bool? StatusTeveInternadoem12Meses { get; set; }

        /// <summary>
        /// Outras práticas integrativas / complementares
        /// </summary>
        [JsonProperty(PropertyName = "statusUsaOutrasPraticasIntegrativasOuComplementares")]
        public bool? StatusUsaOutrasPraticasIntegrativasOuComplementares { get; set; }

        /// <summary>
        /// Usa plantas medicionais
        /// </summary>
        [JsonProperty(PropertyName = "statusUsaPlantasMedicinais")]
        public bool? StatusUsaPlantasMedicinais { get; set; }

        /// <summary>
        /// Diagnóstico mental
        /// </summary>
        [JsonProperty(PropertyName = "statusDiagnosticoMental")]
        public bool? StatusDiagnosticoMental { get; set; }

        /// <summary>
        /// Lista de doenças cardíacas
        /// </summary>
        [JsonProperty(PropertyName = "doencaCardiaca")]
        public IList<int?> DoencaCardiaca { get; set; }

        /// <summary>
        /// Lista de doenças respiratórias
        /// </summary>
        [JsonProperty(PropertyName = "doencaRespiratoria")]
        public IList<int?> DoencaRespiratoria { get; set; }

        /// <summary>
        /// Lista de doenças renais
        /// </summary>
        [JsonProperty(PropertyName = "doencaRins")]
        public IList<int?> DoencaRins { get; set; }

    }
}
