// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Softpark.WS.Test.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetCadastroDomiciliarViewModel
    {
        /// <summary>
        /// Initializes a new instance of the GetCadastroDomiciliarViewModel
        /// class.
        /// </summary>
        public GetCadastroDomiciliarViewModel() { }

        /// <summary>
        /// Initializes a new instance of the GetCadastroDomiciliarViewModel
        /// class.
        /// </summary>
        public GetCadastroDomiciliarViewModel(Guid token, Guid? uuid = default(Guid?), CondicaoMoradiaViewModel condicaoMoradia = default(CondicaoMoradiaViewModel), EnderecoLocalPermanenciaViewModel enderecoLocalPermanencia = default(EnderecoLocalPermanenciaViewModel), bool? fichaAtualizada = default(bool?), int? quantosAnimaisNoDomicilio = default(int?), bool? stAnimaisNoDomicilio = default(bool?), bool? statusTermoRecusa = default(bool?), Guid? uuidFichaOriginadora = default(Guid?), int? tipoDeImovel = default(int?), InstituicaoPermanenciaViewModel instituicaoPermanencia = default(InstituicaoPermanenciaViewModel), IList<int?> animalNoDomicilio = default(IList<int?>), IList<FamiliaRowViewModel> familiaRow = default(IList<FamiliaRowViewModel>), string latitude = default(string), string longitude = default(string))
        {
            Uuid = uuid;
            Token = token;
            CondicaoMoradia = condicaoMoradia;
            EnderecoLocalPermanencia = enderecoLocalPermanencia;
            FichaAtualizada = fichaAtualizada;
            QuantosAnimaisNoDomicilio = quantosAnimaisNoDomicilio;
            StAnimaisNoDomicilio = stAnimaisNoDomicilio;
            StatusTermoRecusa = statusTermoRecusa;
            UuidFichaOriginadora = uuidFichaOriginadora;
            TipoDeImovel = tipoDeImovel;
            InstituicaoPermanencia = instituicaoPermanencia;
            AnimalNoDomicilio = animalNoDomicilio;
            FamiliaRow = familiaRow;
            Latitude = latitude;
            Longitude = longitude;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uuid")]
        public Guid? Uuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public Guid Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "condicaoMoradia")]
        public CondicaoMoradiaViewModel CondicaoMoradia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enderecoLocalPermanencia")]
        public EnderecoLocalPermanenciaViewModel EnderecoLocalPermanencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fichaAtualizada")]
        public bool? FichaAtualizada { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantosAnimaisNoDomicilio")]
        public int? QuantosAnimaisNoDomicilio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stAnimaisNoDomicilio")]
        public bool? StAnimaisNoDomicilio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusTermoRecusa")]
        public bool? StatusTermoRecusa { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uuidFichaOriginadora")]
        public Guid? UuidFichaOriginadora { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tipoDeImovel")]
        public int? TipoDeImovel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instituicaoPermanencia")]
        public InstituicaoPermanenciaViewModel InstituicaoPermanencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "animalNoDomicilio")]
        public IList<int?> AnimalNoDomicilio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "familiaRow")]
        public IList<FamiliaRowViewModel> FamiliaRow { get; set; }

        /// <summary>
        /// Latitude de demarcação do início do cadastro
        /// </summary>
        [JsonProperty(PropertyName = "latitude")]
        public string Latitude { get; set; }

        /// <summary>
        /// Latitude de demarcação do início do cadastro
        /// </summary>
        [JsonProperty(PropertyName = "longitude")]
        public string Longitude { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
        }
    }
}
